package/crossplane.yaml
Signed-off-by: Jean du Plessis <jean@upbound.io>
This avoids telling the user to visit the marketplace when they are already in the marketplace
Fixes #79
I have:
n/a
=> Remove Marketplace self-reference.

.github/workflows/uptest.yml
See https://github.com/upbound/provider-aws/pull/82/files#r997219791
I have:
Needs to be merged to get tested.
=> Fetch submodule after checkout

docs/Quickstart.md
I'll follow up with a PR to make this replacements easier during the release.
I have:
N/A
=> Update remaining versions in docs

.github/workflows/uptest-all.yml, .github/workflows/uptest.yml, Makefile, apis/generate.go, go.mod, go.sum
Update to consume the new Uptest version.
I have:
https://github.com/upbound/provider-aws/actions/runs/3267395313/jobs/5372518821
=> uptest: use the new and public uptest

internal/controller/glue/securityconfiguration/zz_controller.go
Accidentally merged https://github.com/upbound/provider-aws/pull/124 before rebasing. @ezgidemirel 
I have:
=> glue: regenerate to get update

Makefile
Bumping uptest and build submodule to latest.
I have:
I'll test with e2e workflow.
=> Bump to latest uptest and build submodule

examples/cloudsearch/domain.yaml, examples/ec2/instance.yaml, examples/eks/cluster.yaml, examples/eks/identityproviderconfig.yaml
Signed-off-by: ezgidemirel <ezgidemirel91@gmail.com>
We forgot to update existing annotations while separating the Uptest code. 
Fixes #
I have:
N/A
=> Fix Uptest timeout annotation

config/rds/config.go
Add additional connection details:
- endpoint
- reader_endpoint
I have:
Test by building and deploying changes to an AWS EKS cluster and provisioning an RDS Aurora serverless v2 instance
=> Add additional connection details for RDS Cluster

config/externalnamenottested.go
Configure 24 resources without testing. Related issues:
https://github.com/upbound/provider-aws/issues/50
https://github.com/upbound/provider-aws/issues/40
https://github.com/upbound/provider-aws/issues/64
I have:
=> Configure 24 resources without testing

config/externalnamenottested.go
Configure some resources without testing
I have:
=> Configure some resources without testing

config/externalnamenottested.go
Configure some resources without testing part II
I have:
=> Configure some resources without testing II

config/externalnamenottested.go
Added configuration for resources:
Fixes #305 
I have:
=> SSM: configured 10 resources

config/externalnamenottested.go
Configure some resources without testing
I have:
=> Configure some resources without testing III

config/externalnamenottested.go
Configured next resources without testing in `storagegateway` group:
Fixes #307 
I have:
=> storagegateway: Configured 10 resources

config/externalnamenottested.go
Added configuration for 1 resources in the `location` group:
Added configuration for 3 resources in the `mskconnect` group:
Fixes #60 
I have:
=> Location: Add 1 resource, Mskconnect: Add 3 resources

config/externalnamenottested.go
Added configuration for 6 resources in the `imagebuilder` group:
Added configuration for 3 resources in the `inspector` group:
Fixes #61 
I have:
=> imagebuilder: added 6 resources, inspector: added 3 resources

config/externalnamenottested.go
Added configuration for 4 resources in `networkfirewall` group:
Added configuration for 9 resources in `networkmanager` group:
[`aws_networkmanager_connection`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_connection)
Fixes #59 
I have:
=> networkfirewall: Add 4 resources, networkmanager: Add 9 resources

apis/v1alpha1/doc.go, apis/v1alpha1/types.go, apis/zz_register.go, config/provider.go, package/crds/aws.upbound.io_storeconfigs.yaml
Signed-off-by: ezgidemirel <ezgidemirel91@gmail.com>
Fixes ESS alpha feature by adding the scheme.
Fixes #205 
I have:
Created an access key resource and checked Vault:
```
Every 2.0s: kubectl get managed                                                       Ezgis-MacBook-Pro.local: Tue Dec 27 14:53:00 2022
NAME                                       READY   SYNCED   EXTERNAL-NAME      AGE
user.iam.aws.upbound.io/sample-user-ezgi   True    True     sample-user-ezgi   146m
NAME                                             READY   SYNCED   EXTERNAL-NAME          AGE
accesskey.iam.aws.upbound.io/sample-access-key   True    True     AKIAY4AFTTSE7T6MDUPW   10m
```
```
kubectl -n vault-system exec -i vault-0 -- vault kv get /secret/crossplane-system/ess-mr-conn
============== Secret Path …
```
=> Add store config scheme

config/externalnamenottested.go
Add configuration of 14 resources in the `ses` group:
* [`aws_ses_active_receipt_rule_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_active_receipt_rule_set)
* [`aws_ses_configuration_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_configuration_set)
* [`aws_ses_domain_dkim`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_domain_dkim)
* [`aws_ses_domain_identity`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_domain_identity)
* [`aws_ses_domain_identity_verification`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_domain_identity_verification)
* [`aws_ses_domain_mail_from`](https://registry.terraform.io/providers/ha …
=> Add configuration for ses (14),shield (3),signer (2),simpledb (1) groups

config/mq/config.go
Add additional connection details for MQ (RabbitMQ) instances:
- instance_0_endpoint_0
- instance_0_console_url
I have:
Test by building and deploying to an AWS EKS cluster and provisioning an AmazonMQ RabbitMQ cluster and retrieving the new connection details for use in an app
=> Add additional connection details for MQ (RabbitMQ)

config/rds/config.go
Fixes #442 
I have:
Provisioned  `Instance` using crossplane `1.10.1` and a local build, verified `endpoint` value was available
=> Make endpoint available for RDS DB Instance

Makefile
This PR bumps the `crddiff` version to `v0.5.0`. We should be reporting a breaking change in #456.
I have:
Observe build pipelines.
=> Bump crddiff to v0.5.0

examples/docdb/cluster.yaml, examples/docdb/clusterinstance.yaml, examples/ec2/securitygroup.yaml, examples/elasticache/parametergroup.yaml, examples/iam/policy.yaml, examples/iam/role.yaml, examples/mq/broker.yaml, examples/rds/instance.yaml, examples/rds/parametergroup.yaml, examples/s3/bucketpolicy.yaml, examples/sns/topicsubscription.yaml
This PR includes the following changes:
- dbinstance.docdb.aws.crossplane.io : *Added dependencies, annotations, labels*
- dbcluster.docdb.aws.crossplane.io : *Added dependencies, annotations, labels*
- dbclusterparametergroup.docdb.aws.crossplane.io : *Just tested*
- securitygroup.ec2.aws.crossplane.io : *Added dependencies, annotations, labels*
- role.iam.aws.crossplane.io : *Added annotations*
- policy.iam.aws.crossplane.io : *Added annotations, labels*
- dbparametergroup.rds.aws.crossplane.io : *Added annotations, labels*
- bucketpolicy.s3.aws.crossplane.io : *Added dependencies, annotations, labels*
- rdsinstance.database.aws.crossplane.io : *Added dependencies, annotations, labels and removed manual-intervention*
- cacheparametergroup.elasticache.aws.crossplane.io : *Added …
=> Improve examples and test some resources

internal/clients/provider_config.go
Updates the STS client region for WebIdentity role assumption to fall back to global if no region is provided for the managed resource being reconciled. This matches the existing behavior in the STS client construction for assuming a role via chaining.
Follow up to https://github.com/upbound/provider-aws/pull/451
I have:
Verified that the same error experienced in #451 is no longer showing up on IAM Role resources when using the following `ProviderConfig` (which utilizes web identity):
```
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
name: default
spec:
credentials:
source: Upbound
upbound:
webIdentity:
roleARN: arn:aws:iam::REDACTED:role/REDACTED
```
=> Default STS region to global for WebIdentity

apis/glue/v1beta1/zz_generated_terraformed.go, config/glue/config.go, examples/glue/job.yaml
Fixes #651 
I have:
- Ran locally
=> fix for conflicting glue job fields

apis/ec2/v1beta1/zz_generated.deepcopy.go, apis/ec2/v1beta1/zz_generated.resolvers.go, apis/ec2/v1beta1/zz_route_types.go, apis/ec2/v1beta1/zz_securitygrouprule_types.go, config/ec2/config.go, package/crds/ec2.aws.upbound.io_routes.yaml, package/crds/ec2.aws.upbound.io_securitygrouprules.yaml
Add new fields to resolve aws_ec2_managed_prefix_list in aws_route and aws_security_group_rule resources using ref and selector 
Fixes #605
I have:
Tested on our internal aws account
=> feat(ec2): prefix list references in aws_route and aws_security_group_rule

.github/workflows/native-provider-bump.yml
This PR is updating token in `.github/workflows/native-provider-bump.yml`
I have:
=> Update token in native provider bump workflow

apis/firehose/v1beta1/zz_deliverystream_types.go, apis/firehose/v1beta1/zz_generated.deepcopy.go, apis/firehose/v1beta1/zz_generated_terraformed.go, config/firehose/config.go, package/crds/firehose.aws.upbound.io_deliverystreams.yaml
set hec_token as sensitive
Fixes #
I have:
create, update, delete
=> feat(firehose): add hec_token as sensitive

apis/rds/v1beta1/zz_instance_types.go, config/rds/config.go, package/crds/rds.aws.upbound.io_instances.yaml
RDS: Enhance documentation comments for `engine` and `engineVersion`
* Provide URLs for cloud provider doc on supported engine versions
* Remove terraform style parameters and use the actual provider ones
I have:
Checked that CRD spec files contain new comments
=> RDS: Enhance documentation comments for `engine` and `engineVersion`

README.md
The marketplace link for CRD API reference has changed.
Fixes #771
I have:
N/A
=> Fix marketplace link in README.md

apis/sfn/v1beta1/zz_generated.resolvers.go, apis/sfn/v1beta1/zz_statemachine_types.go, config/sfn/config.go
Fix examples/sfn/statemachine.yaml to work with Uptest
Fixes https://github.com/upbound/provider-aws/issues/753
I have:
Uptest: https://github.com/upbound/provider-aws/actions/runs/5421791573
=> Issue 753: Fix examples/sfn/statemachine.yaml to work with Uptest

catalog-info.yaml
Adding backstage configuration file. 
Related: https://github.com/orgs/upbound/projects/108/views/4?pane=issue&itemId=32866664
I have:
Manually added to Backstage instance.
=> Adding backstage configuration file

Makefile, cluster/images/provider-aws/Dockerfile
Bumps the Terraform CLI to `v1.5.5` and consumes the Terraform CLI from https://github.com/upbound/terraform/releases.
I have:
Via uptest
=> Bump Terraform CLI to v1.5.5

cluster/images/provider-aws/Dockerfile
Bumps the provider package base image to `alpine:v3.18.3` to consume the security fixes.
I have:
Via uptest
=> Bump alpine base image to v3.18.3

docs/Configuration.md, docs/Quickstart.md
This PR fixes the warning title.
I have:
=> Fix warning title for monolithic provider

Makefile
Follow up to #916 - missed this override.
I have:
n/a
=> Sync UP_VERSION in Makefile

README.md
This PR fixes broken link for adding new resource
Fixes: https://github.com/upbound/provider-aws/issues/961
I have:
NA
=> Fix broken link for adding new resource

README.md
Add instructions loosly taken from [the github actions](https://github.com/upbound/uptest/blob/main/.github/workflows/provider-publish-service-artifacts.yml), from https://github.com/crossplane/crossplane/discussions/3817 and @haarchri's tips.
I have:
Manually run.
=> README.md: add instruction to build, publish and install

apis/iam/v1beta1/zz_generated_terraformed.go, config/iam/config.go
Signed-off-by: Christopher Haar <christopher.haar@upbound.io>
(cherry picked from commit 765c9502c23b064e0ed9afce049f9718fe0962a9)
Partially fixes: https://github.com/upbound/provider-aws/issues/944
I have:
Uptest: https://github.com/upbound/provider-aws/actions/runs/7030348752
=> [release-0.40] Backport #933

apis/iam/v1beta1/zz_generated_terraformed.go, config/iam/config.go
Signed-off-by: Christopher Haar <christopher.haar@upbound.io>
(cherry picked from commit 765c9502c23b064e0ed9afce049f9718fe0962a9)
Partially fixes: https://github.com/upbound/provider-aws/issues/944
I have:
Uptest: https://github.com/upbound/provider-aws/actions/runs/7030553769
=> [release-0.41] Backport #933

examples/iam/v1beta1/openidconnectprovider.yaml
Updates the example for the iam Open Id Connect Provider to make it work in uptest, using an actual hostname and tls certificate belonging to github actions.
I have:
Uptest on this PR
=> make oidcprovider uptestable

CODEOWNERS, OWNERS.md
This PR adds @mbbush as a maintainer on this repository.
Matt has an extensive record of contributing to this repo and helping those in the community.
I have:
- [-] Run `make reviewable test` to ensure this PR is ready for review.
n/a
=> Add Matt Bush (mbbush) as maintainer

package/crossplane.yaml.tmpl
This PR changes the source code on the marketplace.
I have:
=> Change the value of meta.crossplane.io/source

README.md
This PR updates the slack channel name and issue link in readme
I have:
=> Update slack channel name in readme

apis/mq/v1alpha1/zz_user_types.go, config/mq/config.go, package/crds/mq.aws.upbound.io_users.yaml
This PR adds description to `consoleAccess` field for MQ User.
I have:
=> Add description to consoleAccess field for MQ User

go.mod, go.sum
Bump Upjet to latest version: https://github.com/crossplane/upjet/commit/2e361ad3b6e6b225bbc560ecf7c92e88a7c3ae3a
Partially fixes https://github.com/crossplane-contrib/provider-upjet-aws/issues/1242.
I have:
See Uptest runs linked:
1. [/test-examples="examples/autoscaling/v1beta1/autoscalinggroup.yaml"](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10510484773)
2. [/test-examples="examples/autoscaling/v1beta2/autoscalinggroup.yaml"](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10510490803)
3. [/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10510538491)
4. [/test-examples="examples/ec2/v1beta2/vpcendpoint.yaml"](https://github.com/crossplane-contrib/provider-upjet- …
=> Bump Upjet to commit 2e361ad3b6e6

.github/workflows/uptest-trigger.yaml
The `env` context isn't available in a step's if statement check.
Fixes #
I have:
=> Fix Uptest trigger.

.github/workflows/ci.yml, .github/workflows/uptest-trigger.yaml, go.mod
| stdlib | `go1.23.3` -> `go1.23.5` | go-module | CVE-2024-45341 | Medium |
| stdlib | `go1.23.3` -> `go1.23.5` | go-module | CVE-2024-45336 | Medium |
I have:
=> Update go version to 1.23.5 [SECURITY]

.github/workflows/ci.yml, .github/workflows/uptest-trigger.yaml, go.mod
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2024-45341 | Medium |
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2024-45336 | Medium |
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2025-22866 | - |
I have:
https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/13246005493
=> [release-1.19] Update go version to 1.23.6 [SECURITY]

.github/workflows/ci.yml, .github/workflows/uptest-trigger.yaml, go.mod
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2024-45341 | Medium |
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2024-45336 | Medium |
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2025-22866 | - |
I have:
https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/13246261072
=> [release-1.20] Update go version to 1.23.6 [SECURITY]

.github/workflows/ci.yml, .github/workflows/uptest-trigger.yaml, go.mod
| stdlib | `go1.23.5` -> `go1.23.6` | go-module | CVE-2025-22866 | - |
I have:
https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/13247964051
=> Update go version to 1.23.6 [SECURITY]

.github/workflows/ci.yml, .github/workflows/uptest-trigger.yaml, go.mod
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2024-45341 | Medium |
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2024-45336 | Medium |
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2025-22866 | - |
I have:
https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/13245969941
=> [release-1.18] Update go version to 1.23.6 [SECURITY]

apis/opensearch/v1beta1/zz_domainpolicy_types.go, apis/opensearch/v1beta1/zz_generated.resolvers.go, config/opensearch/config.go, examples/opensearch/v1beta1/domainpolicy.yaml
Fixes #1716 
I have:
I ran uptest locally and will run it again on this PR
=> Fix reference extractor in opensearch.DomainPolicy

.github/workflows/publish-provider-packages.yaml
This PR cherry picks commit c1e2dec0cb5c219b0ef5ba2dec65804bb61f4662 into the crossplane-v2 branch so we can hopefully get a full provider publishing complete 🙏 
I have:
It will be tested when we run publishing, but it has been working well on `main` already 😉 
=> Use larger machines for publish workflow

internal/clients/zz_partitions_gen.go
No manual changes, just rerunning `make generate`
Fixes #
I have:
=> Add aws-eusc partition
