crossplane-contrib/provider-upjet-aws

- Makefile
Kuttl test case will already be outputted to the dump directory with uptest's --test-directory flag passed in CI.
I have:
Will be tested with uptest action.
> Remove kuttl input from cluster_dump target

- .github/workflows/uptest.yml
This PR ensures that issue commenter is a member of Upbound org to trigger the end to end tests.
I have:
Can only be tested after merge.
> Only run e2e tests if commenter is a member of Upbound org

- Makefile
Drops the updoc Makefile target so that it is not triggered during artifact publish.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
I have:
Verified updoc is currently triggered on main:
```
🤖 (provider-aws) GO=go1.19 BRANCH_NAME=release-0.19 make -n publish.artifacts
make -C /home/dan/code/github.com/upbound/provider-aws/cluster/images/provider-aws IMAGE_PLATFORMS=linux/amd64,linux/arm64 IMAGE=xpkg.upbound.io/upbound/provider-aws:v0.19.0 img.publish
echo `date +%H:%M:%S` [ .. ] Pushing package xpkg.upbound.io/upbound/provider-aws:v0.19.0
/home/dan/code/github.com/upbound/provider-aws/.cache/tools/linux_x86_64/up-v0.14.0 xpkg push --package /home/dan/code/github.com/upbound/provider-aws/_output/xpkg/linux_amd64/provider-aws-v0.19.0.xpkg  --package …
```
> Remove updoc Makefile target

- docs/Configuration.md
Signed-off-by: Jean du Plessis <jean@upbound.io>
Removes the invalid instruction that UXP is required to run Upbound AWS official provider.
I have:
n/a
> Remove UXP requirement notice

- .github/workflows/ci.yml
- cmd/generator/main.go
- go.mod
- go.sum
This PR proposes a change where a CSV file of Terraform resource names which are available in the Terraform provider's schema but not generated as managed resources is produced and made available as a Github workflow artifact.
Currently, the artifact is generated when the `generate` make target is run as a dependency (of `check-diff`). This is a little bit implicit and as an alternative we can generate the CSV on its own step. But I did not want to add to our build times (by running `make generate` a second time or computing the diff from the JSON schema and the generated files), and thus preferred to generate the CSV in the `Check Diff` step. 
I have:
Tested with the following workflow run:
https://github.com/upbound/provider-aws/actions/runs/3438916965
> Make not-generated Terraform resources CSV available as a Github workflow artifact

- go.mod
- go.sum
Removes the `replace` statement in go.mod and consumes Upjet's current main HEAD(`6de200a3a8b0ac77c5f9d122f93db26aacd61960`).
I have:
Manually with `make reviewable`
> Consume upjet commit 6de200a3a8b0ac77c5f9d122f93db26aacd61960

- Makefile
- cluster/test/setup.sh
This PR fixes couple of issues with local dev flow with uptest:
- Configures `Test` as default condition
- Splits local deployment as a separate target so that `make uptest` could be called when provider is running externally with `make run` (i.e. previous workflow with `make uptest-local`)
- updates uptest version to latest to get a fix with data source parsing
I have:
```bash
UPTEST_DATASOURCE_PATH=.work/uptest-datasource.yaml UPTEST_EXAMPLE_LIST=examples/codecommit/approvalruletemplateassociation.yaml make e2e
```
Also
```bash
make run
UPTEST_EXAMPLE_LIST=examples/iam/user.yaml make uptest
```
> Fixes and Tweaks with Uptest related targets

- apis/autoscaling/v1beta1/zz_generated_terraformed.go
- config/autoscaling/config.go
Signed-off-by: Christopher Paul Haar <christopherpaul.haar@dkb.de>
we tested today upbound/provider-aws and found one Issue regarding  fields in asg **availability_zones** - looks like this issue has open PRs in crossplane-contrib/provider-jet-aws as well
```
observe failed: cannot run refresh: refresh failed: Conflicting configuration arguments: "availability_zones": conflicts with vpc_zone_identifier: File name: main.tf.json
Conflicting configuration arguments: "vpc_zone_identifier": conflicts with availability_zones: File name: main.tf.json
```
https://github.com/crossplane-contrib/provider-jet-aws/pull/238
Fixes #106
I have:
> fix(asg): fix observed failed availability_zones / vpc_zone_identifier

- config/externalnamenottested.go
This PR removes some resources already configured in `config/externalname.go` but still exist in `config/externalnamenottested.go`
I have:
The example manifests already exist for the respective resources, which imply they were previously validated.
> Remove already configured resources from externalnamenottested.go

- .github/workflows/ci.yml
- cmd/generator/main.go
Prints a coverage statistics line in the CI pipeline. Some previous discussions are [here](https://github.com/upbound/provider-aws/pull/139).
I have:
A new step following the `Check Diff` step now prints the statistics in the `CI` Github workflow:
> Print coverage statistics

- docs/Quickstart.md
- docs/quickstart.sh
This PR updates the quickstart guide by:
- Updating provider version to the latest
- Fixing the _Bash script_ mode, which is otherwise not asking for input and creating empty creds. 
Initially identified in https://github.com/upbound/provider-aws/issues/186 but not fixing the issue there.
I have:
By following the quickstart steps.
> Updates in the Quickstart Guide

- .github/workflows/ci.yml
- Makefile
This PR introduces a new `report-breaking-changes` CI job that detects and reports breaking API changes between the two revisions of a generated managed resource definition using the crddiff tool. 
Currently, we would like to detect and report breaking API changes and not prevent them. In later iterations, we would like trigger uptests on breaking changes.
I have:
Validated using a change that introduces:
- A new CRD
- A CRD with a non-breaking API change
- A CRD with a breaking API change
If no API changes in the CRDs (breaking or non-breaking) are detected, then the reporting step is skipped:
> Report CRD breaking API schema changes with a report-breaking-changes CI job

- apis/ec2/v1beta1/zz_generated_terraformed.go
- config/ec2/config.go
- examples/ec2/securitygrouprule-self-true.yaml
Add late init to `self` and `source_security_group_id`
Fixes #228
Signed-off-by: Yury Tsarev <yury@upbound.io>
I have:
```
k apply -f examples/ec2/securitygrouprule-self-true.yaml
```
```
k get managed
NAME                                        READY   SYNCED   EXTERNAL-NAME          AGE
securitygroup.ec2.aws.upbound.io/test-vpc   True    True     sg-00c2b14d55b3da787   10m
NAME                                READY   SYNCED   EXTERNAL-NAME           AGE
vpc.ec2.aws.upbound.io/sample-vpc   True    True     vpc-0f8da654a40cb68cb   10m
NAME                                                          READY   SYNCED   EXTERNAL-NAME       AGE
securitygrouprule.ec2.aws.upbound.io/test-vpc-securitygroup   True    True     sgrule-2687506433   10m
```
> Fix late init of SecurityGroupRule with `self: true`

- Makefile
- cluster/test/setup.sh
This PR proposes a change that would allow us to utilize a second IAM user for cross-account resource uptesting when the repo is properly configured with a second credentials environment variable.
A second `ProviderConfig.aws` named `peer` is provisioned in a different AWS account than the `default` `ProviderConfig`'s account for cross-account testing.
NOTE: This PR introduces a breaking change in the expected syntax for the Github repo secret `UPTEST_CLOUD_CREDENTIALS`, and the corresponding env. variable `UPTEST_CLOUD_CREDENTIALS` when running uptest locally with the associated make targets. It now has the following syntax:
```
DEFAULT='[default]
aws_access_key_id = REDACTED
aws_secret_access_key = REDACTED'
PEER='[default]
aws_access_key_id = REDACTED
aws_secret_access_key = REDACTED' …
```
> Use UPTEST_CLOUD_CREDENTIALS Github repo secret to enable cross-account resource uptesting

- config/externalnamenottested.go
Add untested configurations for the following resources:
- aws_service_discovery_service
- aws_elasticache_security_group
- aws_elasticache_global_replication_group
- aws_elasticache_user_group_association
- aws_ram_principal_association
- aws_ram_resource_association
- aws_ram_resource_share
- aws_ram_resource_share_accepter
- aws_sns_platform_application
- aws_sns_sms_preferences
- aws_sns_topic_policy
- aws_ecs_task_set
- aws_grafana_license_association
- aws_gamelift_game_server_group
I have:
N.A.
> Add more untested configurations from the service_discovery, elasticache, ram , sns, ecs, grafana and gamelift groups

- examples/cloudwatchevents/target.yaml
Signed-off-by: Sergen Yalçın <yalcinsergen97@gmail.com>
This PR adds manual-intervention annotation for necessary resources in EventBridge resources.
I have:
Uptest
`aws_cloudwatch_event_api_destination`, `aws_cloudwatch_event_archive`, `aws_cloudwatch_event_bus`, `aws_cloudwatch_event_bus_policy`, `aws_cloudwatch_event_connection`, `aws_cloudwatch_event_permission`, `aws_cloudwatch_event_rule`, `aws_cloudwatch_event_target`: https://github.com/upbound/provider-aws/actions/runs/3684459356
> Add manual-intervention annotation for necessary resources in EventBridge resources

- apis/ec2/v1beta1/zz_generated_terraformed.go
- config/ec2/config.go
- examples/ec2/securitygrouprule-self-true.yaml
* Extend LateInit field list following the tf documentation https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule#self
* Group examples with the special annotation
Signed-off-by: Yury Tsarev <yury@upbound.io>
Follow up to #229 
I have:
```
make run
k apply -f examples/ec2/securitygrouprule-self-true.yaml`
k get -f examples/ec2/securitygrouprule-self-true.yaml
NAME                                READY   SYNCED   EXTERNAL-NAME           AGE
vpc.ec2.aws.upbound.io/sample-vpc   True    True     vpc-0e32df8eeb7da09f8   9m39s
NAME                                        READY   SYNCED   EXTERNAL-NAME          AGE
securitygroup.ec2.aws.upbound.io/test-vpc   True    True     sg-0d07d08552c9afea9   9m39s
NAME …
```
> Amend SecurityGroupRule late init fix

- config/externalname.go
- examples/kms/alias.yaml
Signed-off-by: Steven Borrelli <steve@borrelli.org>
Update name/external-name handling on KMS alias. 
Fixes #24
I have:
I've tested locally using the following manifest to test importing external names of the format "name" and "alias/name":
```yaml
---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
name: official-provider-google
spec:
forProvider:
region: us-west-2
description: Key For Testing containeraws.gcp.upbound.io resources
---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Alias
metadata:
name: official-provider-google
spec:
forProvider:
region: us-west-2
targetKeyIdRef:
name: official-provider-google
---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
name: test-import
spec:
forProvider:
region: us-west-2
description: Key For Testing 
---
apiVersion: …
```
> fix kms alias name

- config/externalnamenottested.go
Added configuration for 11 resources in the `waf` group:
Added configuration for 10 resources in the `wafregional` group:
extracted from https://github.com/upbound/provider-aws/issues/53
Fixes #36 
I have:
> waf: Configured 11 resources; wafregional: Configured 10 resources

- config/externalnamenottested.go
Add configuration of 2 resources in the `transfer` group:
Fixes #41 
I have:
> Configured transfer(2) group resources

- config/externalnamenottested.go
Add configuration of 2 resource in the `elasticbeanstalk` group:
Add configuration of 1 resource in the `imagebuilder` group:
Fixes #400 
I have:
> Add configuretion for elasticbeanstalk(2), imagebuilder(1)

- apis/efs/v1beta1/zz_generated.deepcopy.go
- apis/efs/v1beta1/zz_generated.resolvers.go
- apis/efs/v1beta1/zz_mounttarget_types.go
- config/efs/config.go
- examples/efs/mounttarget.yaml
- package/crds/efs.aws.upbound.io_mounttargets.yaml
* MountTarget of official provider was missing the selectors for SecurityGroup
* It is regression assuming scenario of migration from the community provider-aws, as the references are there https://marketplace.upbound.io/providers/crossplane-contrib/provider-aws/v0.33.0/resources/efs.aws.crossplane.io/MountTarget/v1alpha1#doc:spec-forProvider-securityGroupsRefs
Signed-off-by: Yury Tsarev <yury@upbound.io>
I have:
uptest with the comment below
> Add missing SecurityGroup selectors to EFS MountTarget

- config/externalname.go
I inverted the `transit_gateway_attachment_id` and `transit_gateway_route_table_id` in the `aws_ec2_transit_gateway_route_table_propagation`  external name. Because IDs were inverted as suspected in #434 
Fixes #434
I have:
I deployed the freshly built provider in my setup, it created the expected `TransitGatewayRouteTablePropagation`.
> Fix ec2: `TransitGatewayRouteTablePropagation` inverted `transit_gateway_attachment_id` and `transit_gateway_route_table_id`ids

- config/rds/config.go
Signed-off-by: josephferrero <joeferrero14@gmail.com>
Added `username` to the RDS instance connection secret.
Fixes #442 for the request to add the username to the connection secret. Note that the port is now included in the endpoint address, so it is not required to achieve feature parity with the `database.aws.crossplane.io/v1beta1` provider.
I have:
I have run `make local-deploy` and created an RDS instance in AWS to test creation of the secret.
> add username to rds connection details

- internal/clients/provider_config.go
Fixes #215
currently assumeRoleChain doesn't work for IAM resources because IAM resources don't require a region. the error is
```
cannot get terraform setup: failed to retrieve aws credentials from aws config: failed to refresh cached credentials, operation error STS: AssumeRole, failed to resolve service endpoint, an AWS region is required, but was not found
```
this change adds a fallback to "aws-global" region for STS requests in cases where no region is set in the managed resource
I have:
I built the provider w/ the fix, installed it in my environment, and confirmed I no longer get the 'region is required' error
> allow using assumeRoleChain with IAM resources

- apis/rds/v1beta1/zz_generated.resolvers.go
- apis/rds/v1beta1/zz_instance_types.go
- config/rds/config.go
- examples/rds/instance.yaml
Fixes #411 
This PR changes the auto-injected reference extractor for the `KMSKeyID` of `rds.Instance` to `common.ARNExtractor`. Also adds a `kms.Key` as a dependency to the example manifest of `rds.Instance`.
I have:
The ARN is correctly resolved now:
```yaml
spec:
deletionPolicy: Delete
forProvider:
kmsKeyId: arn:aws:kms:us-west-1:<account>:key/f3766940-bfde-4304-bb31-ea04be153547
kmsKeyIdRef:
name: sample-key
kmsKeyIdSelector:
matchLabels:
testing.upbound.io/example-name: sample-key
```
Corresponding uptest run: https://github.com/upbound/provider-aws/actions/runs/4113302303
> Fix KMSKeyID reference extractor for Instance.rds

- .github/workflows/ci.yml
- .github/workflows/uptest-all.yml
Bumps `fkirc/skip-duplicate-actions` Github action to v5.3.0. Also remove usages of the deprecated `set-output` and `save-state` Github commands:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
We also bump the `actions/cache` and the `docker/setup-buildx-action` actions to `v3` and `v2`, respectively, as the current versions make use of the deprecated `save-state` command.
I have:
The new dependency's been available in this run:
https://github.com/upbound/provider-aws/actions/runs/4111881233/jobs/7096129032
And in the following run with an amended commit, the jobs were successfully skipped:
https://github.com/upbound/provider-aws/actions/runs/4111973225/jobs/7096326530
Regarding the `actions/cache` dependency, Github no longer …
> Bump fkirc/skip-duplicate-actions Github action to v5.3.0

- config/rds/config.go
adds more fields  ( host , address, port )for rds instance connection details. We need this to pass them along to provider-sql and the upcoming upjet [generated provider-postgresql](https://github.com/alexinthesky/provider-postgresql) ). I guess this comes handy as the tf providerconfig asks for separate host and port, as most of the PG clients )
Fixes #
I have:
ran it locally against
> add more fields to connection details

- apis/rds/v1beta1/zz_generated.deepcopy.go
- apis/rds/v1beta1/zz_instance_types.go
- config/rds/config.go
- config/rds/config_test.go
- examples/rds/instance.yaml
- go.mod
- package/crds/rds.aws.upbound.io_instances.yaml
Adds ability to auto-generate password. Users need to opt-in by setting `autoGeneratePassword` as `true` and should have a `Secret` reference. It will create if the referenced `Secret` does not exist and it will populate if it doesn't have the password for the given key.
I have:
Unit tests, local end-to-end test and Uptest.
> rds.instance: add ability to auto-generate password in referenced secret

- apis/appstream/v1beta1/zz_fleet_types.go
- apis/gamelift/v1beta1/zz_fleet_types.go
- apis/sagemaker/v1beta1/zz_devicefleet_types.go
- config/appstream/config.go
- config/gamelift/config.go
- config/sagemaker/config.go
- go.mod
- go.sum
- package/crds/appstream.aws.upbound.io_fleet.yaml
- package/crds/gamelift.aws.upbound.io_fleet.yaml
- package/crds/sagemaker.aws.upbound.io_devicefleet.yaml
Fixes #646
Depends on: https://github.com/upbound/upjet/pull/184
Prior to the `v0.32.0` release, we bumped the `sigs.k8s.io/controller-tools` to `v0.11.3` together with some other Kubernetes libraries such as the controller-runtime. This introduced a change where the plural names of custom (managed) resources whose names end with `fleet` to have new plural names due to https://github.com/kubernetes-sigs/controller-tools/pull/660. Since with the official providers we are generating & installing new CRDs, this results in a new CRD being installed by the Crossplane package manager with name, for example, `fleets.gamelift.aws.upbound.io` with `provider-aws@v0.32.0` in addition to the already installed CRD with name `fleet.gamelift.aws.upbound.io` from `provider-aws@v0.31.0`.  In my tests from …
> Configure plural names for resources whose kind names end with "fleet"

- apis/ec2/v1beta1/zz_generated.resolvers.go
- apis/ec2/v1beta1/zz_launchtemplate_types.go
- config/ec2/config.go
- examples/ec2/launchtemplate_encrypted.yaml
- using ARN instead of ID for kmsKeyId in launchTemplate
Fixes #637
I have:
created resource:
```
NAME                                        READY   SYNCED   EXTERNAL-NAME          AGE
launchtemplate.ec2.aws.upbound.io/example   True    True     lt-0e0a70effb499371b   81s
NAME                                        READY   SYNCED   EXTERNAL-NAME                          AGE
key.kms.aws.upbound.io/launchtemplate-key   True    True     644d0c73-0ec8-47a4-8e3b-0c3ed203b89d   3m49s
```
```
kubectl describe launchtemplate.ec2.aws.upbound.io/example 
Name:         example
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2023-04-01T19:40:45+02:00
crossplane.io/external-create-succeeded: 2023-04-01T19:40:45+02:00
crossplane.io/external-name: …
```
> fix(launchTemplate): fixed kmsKeyId to use ARN

- config/externalname.go
missed after rebase and squash one needed commit https://github.com/upbound/provider-aws/pull/591 sorry for that 
the external-name is key, seperated by a comma not a underscore 
Fixes #
I have:
created, updated and removed resource
```
tag.ec2.aws.upbound.io/xxxx-dr9p7-gw82d True    True     sg-08c821268fffc30c6,karpenter.sh/discovery   4d2h
tag.ec2.aws.upbound.io/xxxx-8hg7t-v5kn8 True    True     sg-0a4cc05e3de099b5b,karpenter.sh/discovery   4d2h
tag.ec2.aws.upbound.io/xxxx-fgjlt-7f2dh True    True     sg-0b48617ae1087419d,karpenter.sh/discovery   4d2h
tag.ec2.aws.upbound.io/xxxx-wbp2s-v9phw True    True     sg-06253ac86f8e0f474,karpenter.sh/discovery   4d2h
tag.ec2.aws.upbound.io/xxxx-fpdpz-kcw7d True    True     sg-018077a7a173e6339,karpenter.sh/discovery   4d2h …
```
> fix(ec2_tag): fix identifier and key, seperated by a comma not a underscore

- config/iam/config.go
add username and password for iam accesskey connection secret like community provider-aws 
community provider-aws:
```
apiVersion: v1
data:
password: *****
username: *****
```
official provider-aws:
```
apiVersion: v1
data:
attribute.secret: *****
attribute.ses_smtp_password_v4: *****
```
after that PR we have 2 additional keys for official provider-aws:
```
apiVersion: v1
data:
attribute.secret: *****
attribute.ses_smtp_password_v4: *****
password: *****
username: *****
```
think today its not possible to run an uptest action for this `AdditionalConnectionDetailsFn` we have one open issue for that: https://github.com/upbound/uptest/issues/82
Fixes #479
I have:
create user.yaml and checked secret
```
NAME                                  READY   SYNCED   EXTERNAL-NAME   AGE …
```
> fix(iam): added username and password for iam accesskey connection-secret

- apis/elbv2/v1beta1/zz_generated_terraformed.go
- config/elbv2/config.go
- examples/elbv2/lb.yaml
fix the following issue:
```
message: 'cannot update managed resource: LBTargetGroup.elbv2.aws.upbound.io "xxx-hhncg-cgtlp"
is invalid: [spec.forProvider.targetFailover.onDeregistration: Required value,
spec.forProvider.targetFailover.onUnhealthy: Required value]'
```
add `target_failover` for `LateInitializer.IgnoredFields` - this field is optional: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group#target_failover
without this PR we see the following in temp statefile:
```
"target_failover": [
{
"on_deregistration": null,
"on_unhealthy": null
}
],
```
Fixes #663
I have:
create `aws_lb_target_group` before this PR
```
kubectl get lbtargetgroup.elbv2.aws.upbound.io                          
NAME                                  READY   SYNCED …
```
> fix(lateinit): `aws_lb_target_group` target_failover

- apis/ram/v1beta1/zz_generated.deepcopy.go
- apis/ram/v1beta1/zz_generated.resolvers.go
- apis/ram/v1beta1/zz_resourceassociation_types.go
- config/provider.go
- config/ram/config.go
- examples-generated/ram/resourceassociation.yaml
- examples/ram/resourceassociation.yaml
- package/crds/ram.aws.upbound.io_resourceassociations.yaml
the problem is that `resource_arn` can have a selector / reference to multiple resource types checkout #662
Fixes #662
I have:
up-test is not possible because of manual-intervention
> fix(ram): skip reference/selector for resource_arn for aws_ram_resource_association

- apis/ecs/v1beta1/zz_service_types.go
- config/ecs/config.go
- examples/ecs/service-static-cluster.yaml
- package/crds/ecs.aws.upbound.io_services.yaml
fixed the description for ecs_service cluster field - we need the cluster name / short-id instead of ARN - ref & selector working as expected as mentioned by @dverveiko in #624 
Fixes #624
I have:
applied new example:
```
NAME                                                 READY   SYNCED   EXTERNAL-NAME             AGE
cluster.ecs.aws.upbound.io/example-cluster-service   True    True     example-cluster-service   4m2s
NAME                                         READY   SYNCED   EXTERNAL-NAME     AGE
service.ecs.aws.upbound.io/example-service   True    True     example-service   4m2s
NAME                                                           READY   SYNCED   EXTERNAL-NAME   AGE
taskdefinition.ecs.aws.upbound.io/example-service-definition   True    True     sampleservice   4m2s
```
> fix(ecs-service): #624 fix description of ecs service cluster field

- Makefile
- package/auth.yaml
- package/crossplane.yaml
Adds the auth group annotation to the crossplane.yaml.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Adds documentation and schema info for ProviderConfig auth.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Updates the up version to v0.16.0.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
I have:
Built locally and inspected image contents.
> Add ProviderConfig auth documentation

- .github/workflows/publish-service-artifacts.yml
Consumes reusable workflows introduced in https://github.com/upbound/uptest/pull/94
I have:
Manually tested on `turkenf/uptest` and `turkenf/provider-aws`
> Add caller workflow for publishing service artifacts

- Makefile
- config/networkfirewall/config.go
While testing a new resource in provider-aws, after running `make run` in my local, the `ready` and `synced` status of the resource remained empty. I didn't encounter any error message in the description and when I used `monolith` package instead of `provider` in local run, the problem was solved.
I have:
> Use monolith for local run

- config/externalname.go
- examples/appflow/flow.yaml
This PR removes `.parameters.region` references from external-name configuration template bodies for the following resources:
- aws_prometheus_rule_group_namespace
- aws_cloudformation_stack
- aws_appflow_flow
- aws_networkmanager_transit_gateway_connect_peer_association
- aws_networkmanager_customer_gateway_association
- aws_evidently_segment
Fixes: https://github.com/upbound/provider-aws/issues/673
I have:
- `aws_prometheus_rule_group_namespace`: Manually, Uptest(https://github.com/upbound/provider-aws/actions/runs/5003502943)
```
NAME                                         READY   SYNCED   EXTERNAL-NAME   AGE
rulegroupnamespace.amp.aws.upbound.io/demo   True    True     demo            6m16s
```
- `aws_cloudformation_stack`: Manually, …
> Remove `.parameters.region` references from external-name configuration template bodies

- config/rds/config.go
- examples/rds/cluster.yaml
Add next fields: write the username and port field to the connection secret
Fixes https://github.com/upbound/provider-aws/issues/574
I have:
Uptest: https://github.com/upbound/provider-aws/actions/runs/5212568558
Manually
> Fix for the issue 574: rds: DBCluster writeConnectionSecret missing fields

- config/rds/config.go
- config/rds/config_test.go
Otherwise, the `Secret` is left in the cluster even if the `Instance` is completely gone from the cluster.
I have:
Manually and with unit tests.
> rds.instance: add owner reference if the input secret is created by us

- apis/acm/v1beta1/zz_generated_terraformed.go
- config/acm/config.go
- examples/acm/certificate.yaml
fix 464 issue: acm:Certificate Late init fields should be skipped - cannot run refresh
Ignored next attributes:
"validation_method",
"key_algorithm",
"certificate_body",
"options.certificate_transparency_logging_preference",
"subject_alternative_names"
Fixes https://github.com/upbound/provider-aws/issues/464
I have:
Manually - acm:Certificate requires a valid certificate and privateKeySecret
> fix 464 issue: acm:Certificate Late init fields should be skipped - cannot run refresh

- package/crossplane.yaml.tmpl
To support Upbound Marketplace search indexing behaviour, the family label should only be applied on subpackages and not the config provider.
xref https://github.com/upbound/provider-gcp/pull/315
I have:
Build xpkg and extracted annotated layer to confirm the label below is only present on subpackages.
```
labels:
pkg.crossplane.io/provider-family: provider-family-aws
```
> Remove family label from the config provider for proper search indexing

- Makefile
* The current instructions in Makefile was containing outdated instructions before introdcution of the `PEER` test credentials
* Update examples to cover both single `DEFAULT` and multicred `PEER` export examples
I have:
by testing the `export` command together with uptest `make e2e` local invocation in #463
> Provide up-to-date UPTEST_CLOUD_CREDENTIALS export examples

- apis/ec2/v1beta1/zz_generated_terraformed.go
- config/ec2/config.go
While working on [this issue](https://github.com/upbound/provider-aws/issues/602), I got the following error while trying to create the `ec2.Instance` resource:
```
message: |-
observe failed: cannot run refresh: refresh failed: Conflicting configuration arguments: "cpu_core_count": conflicts with cpu_options.0.core_count
Conflicting configuration arguments: "cpu_options.0.core_count": conflicts with cpu_core_count
Conflicting configuration arguments: "cpu_options.0.threads_per_core": conflicts with cpu_threads_per_core
Conflicting configuration arguments: "cpu_threads_per_core": conflicts with cpu_options.0.threads_per_core
```
These two parameters(`cpu_core_count`, `cpu_threads_per_core`) were deprecated in [version 4.66.0](https://registry.terraform.io/providers/hashicorp/aws/4.66.0/doc …
> Fix conflicting parameters for `ec2.Instance` resource

- config/externalname.go
- examples/iam/policy-with-path.yaml
Terraform uses the policy path in the `tfstate` id, and name (derived from the ID) must match [\w+=,.@-]. Both are bugs in v0.36.0, both are fixed in this PR.
Fixes #742 
I have:
Tested by running locally against existing non-ready resources and by creating new resources with and without paths.
> fix(iam): Policy ID should contain path and the external-name derived from the ID should be the name part only

- config/externalname.go
KMS alias ID should be used from provider (incudes /alias prefix).
Fixes #722 
I have:
Tested by running the build kms provider against a cluster with KMS aliases in a non-ready state due to ID mismatch.
> fix(kms): Alias ID for tfstate should begin with "alias/"

- config/provider.go
Fixes #
The configuration of the following two lines is the same in `Provider.go`, and the configuration of 128 lines has been deleted.
https://github.com/upbound/provider-aws/blob/c0ff895807d65912ee690a7bc0f8ac01e676827e/config/provider.go#L128
https://github.com/upbound/provider-aws/blob/c0ff895807d65912ee690a7bc0f8ac01e676827e/config/provider.go#L130
I have:
> Remove duplicated references injector config

- cluster/images/provider-aws/Makefile
Added the BUILD_ARGS environment variable to the Makefile img.build stage to allow for `http_proxy` environment variables.
Fixes #754 
I have:
`make build` behind a network proxy successfully generates the docker images
> Handle build environment variables for proxy access

- config/externalname.go
* In a current state the instantiation of `UserPoolClient` fails with
```
cannot run refresh: refresh failed: reading Amazon Cognito IDP (Identity Provider) User Pool Client (): InvalidParameter: 1 
validation error(s) found.
- minimum field size of 1, DescribeUserPoolClientInput.ClientId.
```
unless we explicitly set the `external-name` annotation. See #752 for more debugging data
* This change will preset the `id` with `spec.forProvider.name` to avoid the validation failure. The `id` will be populated eventually with the dynamic value from the cloud provider
* I also tried to follow the doc at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool_client#import but it seems to be wrong in practice:
If we use smth like
``` …
```
> CognitoIDP[UserPoolClient]: Avoid underlying provider validation failure

- package/auth.yaml
A follow-up to https://github.com/upbound/provider-gcp/pull/329 disabling Secrets as a part of auth.yaml configuration
I have:
> feat(auth): disable configuring auth with Secrets

- apis/mq/v1beta1/zz_broker_types.go
- apis/mq/v1beta1/zz_generated.deepcopy.go
- apis/mq/v1beta1/zz_generated.resolvers.go
- config/mq/config.go
- examples-generated/mq/broker.yaml
- examples/mq/broker.yaml
- examples/mq/testhooks/delete-broker.sh
- package/crds/mq.aws.upbound.io_brokers.yaml
Missing selector in Broker resource for selecting security groups: add selectors for the securityGroup
Now can use next selectors:
securityGroupRefs
securityGroupSelector
Fixes https://github.com/upbound/provider-aws/issues/726
I have:
Manually
Uptests: https://github.com/upbound/provider-aws/actions/runs/5507977809
> Fix issue 726: Missing selector in Broker resource for selecting security groups 

- config/cloudwatchlogs/config.go
- examples/cloudwatchlogs/group.yaml
skip `name_prefix` in `aws_cloudwatch_log_group` and enhance example
Fixes #795
I have:
create, loop and delete
```
kubectl describe group.cloudwatchlogs.aws.upbound.io/example                            
Name:         example
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2023-07-21T11:29:11+02:00
crossplane.io/external-create-succeeded: 2023-07-21T11:29:11+02:00
crossplane.io/external-name: example
upjet.crossplane.io/provider-meta: null
API Version:  cloudwatchlogs.aws.upbound.io/v1beta1
Kind:         Group
Metadata:
Creation Timestamp:  2023-07-21T09:29:01Z
Finalizers:
finalizer.managedresource.crossplane.io
Generation:        2
Resource Version:  93856
UID:               552d1988-c4fe-4a47-afe5-47e7c58d4e44
Spec:
Deletion Policy:  Delete
For …
```
> fix(aws_cloudwatch_log_group): skip name_prefix lateinit

- apis/cognitoidp/v1beta1/zz_generated_terraformed.go
- config/cognitoidp/config.go
…onfiguration conflicts
Fix late init issue for AWS Cognito User Pool:
message: |-
observe failed: cannot run refresh: refresh failed: Conflicting configuration arguments: "email_verification_subject": conflicts with verification_message_template.0.email_subject
Conflicting configuration arguments: "verification_message_template.0.sms_message": conflicts with sms_verification_message
Conflicting configuration arguments: "verification_message_template.0.email_message": conflicts with email_verification_message
Conflicting configuration arguments: "verification_message_template.0.email_subject": conflicts with email_verification_subject
Conflicting configuration arguments: "sms_verification_message": conflicts with verification_message_template.0.sms_message
Conflicting configuration …
> Fix issue716: AWS Cognito User Pool - Verification Message Template configuration conflicts

- .github/workflows/scan.yml
Adds a scheduled trivy scan for supported images, by default it scans only the latest released image, but can be configured either when running manually using a dedicated input or by changing the env variable to change the scheduled scan behaviour.
See https://github.com/crossplane/crossplane/pull/3815 for more details about the Security tab.
Should be merged after https://github.com/upbound/uptest/pull/84 as it points to the workflow added there using directly the `main` branch.
I have:
See https://github.com/upbound/uptest/pull/84 "How has this code been tested" section for screenshots and example runs.
> ci: scheduled trivy scan

- docs/Configuration.md
- docs/Quickstart.md
(cherry picked from commit ce875a05c2d1757ee6a1aab6f54ee696f3e81be4)
Backport of https://github.com/upbound/provider-aws/pull/848 to release-0.39.
> [Backport release-0.39] Fix warning title for monolithic provider

- apis/firehose/v1beta1/zz_generated_terraformed.go
- config/firehose/config.go
When utilizing the official provider for the Firehose delivery stream, you can observe the CPU and memory consumption as follows:
```
kubectl top pods -n crossplane-system | grep "firehose"
official-provider-aws-firehose-4be7907cab90-65bf966f6f-g24kf   6414m    3150Mi
```
all Firehose delivery stream resources `Synced` and `Ready` `true`
```
dr9p7-v27jz True  True   arn:aws:firehose:eu-central-1:123456789101:deliverystream/eks-logging-to-splunk 
8hg7t-g2xl6 True  True   arn:aws:firehose:eu-central-1:123456789111:deliverystream/eks-logging-to-splunk 
fgjlt-8wblc True  True   arn:aws:firehose:eu-central-1:123456789121:deliverystream/eks-logging-to-splunk 
wbp2s-szw9g True  True   arn:aws:firehose:eu-central-1:123456789131:deliverystream/eks-logging-to-splunk 
fpdpz-jcvbf True  True …
```
> fix(lateinit): skip version_id for firehose deliverystream

- apis/ec2/v1beta1/zz_generated_terraformed.go
- config/ec2/config.go
- examples/ec2/vpc-ipampool.yaml
When configuring a VPC with an IPAM pool and a netmask length, the ipv4 cidr block must not be late initialized. 
Fixes #879 
I have:
Local testing
`uptest e2e examples/ec2/vpc-ipampool.yaml`
> ignore cidr_block on lateinitialize to avoid conflicts when using ipam

- apis/v1beta1/types.go
- internal/clients/aws.go
- package/crds/aws.upbound.io_providerconfigs.yaml
This PR adds the `skip_region_validation` field to the AWS ProviderConfig as per https://registry.terraform.io/providers/hashicorp/aws/2.47.0/docs#skip_region_validation
Fixes #812: Support skipping region validation
I have:
Built custom image using the following:
```
make submodules
export DOCKER_REGISTRY=myregistry/myrepo
export BUILD_REGISTRY=myregistry/myrepo
export XPKG_REG_ORGS=myregistry/myrepo
export REGISTRY_ORGS=myregistry/myrepo
make build.all publish BRANCH_NAME=main SUBPACKAGES="s3 config"
```
Created aws family Provider and s3 Provider using newly built test images:
```
NAME                  INSTALLED   HEALTHY   PACKAGE                                            AGE
provider-aws-family   True        True      myregistry/myrepo/provider-family-aws:v0.37.0      53m …
```
> Add option to skip region validation

- docs/family/Configuration.md
- docs/family/Quickstart.md
- docs/monolith/Configuration.md
- docs/monolith/Quickstart.md
- docs/quickstart.sh
Fix #590: S3 and Lightsail APIs have their own “buckets” resources. Quickstart document creates an S3 bucket. When `kubectl get buckets` command is run, though, Lightsail resources are listed. Such behavior confuses users, especially newcomers to crossplane, who expect to see their S3 buckets instead. 
I have:
I couldn't run `make reviewable test`, because of [IS#737](https://github.com/upbound/provider-aws/issues/737). I hope that updating only documentation won't cause any problems.
I've followed quickstart document and manually run shell commands. I've used a local [kind](https://kind.sigs.k8s.io) cluster.
> Resolve name collision between S3 and Lightsail in quickstart

- Makefile
- cluster/images/provider-aws/Makefile
Depends on: https://github.com/upbound/build/pull/241
Currently when an e2e test is triggered in `upbound/provider-aws`, the test is run with the monolithic provider (`upbound/provider-aws`) package built from the feature branch.
This omits the family resource providers (not a problem from the resource configuration validation perspective because both the monolith and the corresponding resource provider utilize the same resource configuration) but the built family resource package itself is not tested).
Another issue that's the main motion of the proposed changes in this PR is that the number of CRDs installed with the monolithic package cause noise in the tests (pod restarts, timeouts at various levels, etc.). 
This PR proposes to switch to the family resource providers when running …
> Uptest family providers

- package/auth.yaml
Fixes https://github.com/upbound/squad-upbound-cloud/issues/1295, where a link in the Upbound console is broken due to an extra character in `auth.yaml`.
I have:
N/A
> Fix trailing apostrophe breaking a hyperlink

- .github/workflows/publish-service-artifacts.yml
This PR parameterizes the image registry and repo, the branch name and the version used for building and publishing the provider packages so that we can still use the reusable workflow `Provider Publish Service Artifacts` for publishing packages to repositories other than `xpkg.upbound.io/upbound` and with customizable version strings.
I have:
Parts of the underlying reusable workflow has been tested in another organization. The calling workflow has not been tested.
> Add "branch_name", "version" and "regorg" parameters to the "Publish Service Artifacts" workflow

- apis/iam/v1beta1/zz_generated_terraformed.go
- config/iam/config.go
description is here: https://github.com/upbound/provider-aws/issues/929#issuecomment-1774063901
skip managed_policy_arns for late init
Fixes #929
I have:
Manual: https://github.com/upbound/provider-aws/issues/929#issuecomment-1774063901
Uptest: https://github.com/upbound/provider-aws/actions/runs/6611409372
> fix(iam-role): ignore managed_policy_arns in late init

- config/externalname.go
- examples/apigatewayv2/stage.yaml
Sets the external-name configuration of the `MetricFilter.cloudwatchlogs` resource to `config.NameAsIdentifier`. Reconciliation of the resource currently fails as follows:
```yaml
- lastTransitionTime: "2023-10-31T15:07:53Z"
message: 'observe failed: cannot run refresh: refresh failed: reading CloudWatch
Logs Metric Filter (dada:yada): InvalidParameterException: 1 validation error
detected: Value ''dada:yada'' at ''filterNamePrefix'' failed to satisfy constraint:
Member must satisfy regular expression pattern: [^:*]*: '
reason: ReconcileError
status: "False"
type: Synced
```
This PR also adds an example manifest for the `Stage.apigatewayv2` resource. Import tests for this resource are failing as follows:
```yaml
- lastTransitionTime: "2023-10-31T17:07:24Z"
logger.go:42: 17:09:25 | …
```
> Fix MetricFilter.cloudwatchlogs external-name configuration

- config/s3/config.go
Added the s3 arn,id and region to the connection details so that the value will appear in the secret created by writeConnectionSecretToRef
Fixes #
#886 
I have:
Tested with [uptest](https://github.com/upbound/provider-aws/pull/951/checks) and Manually:
```
> kubectl get secrets/test-bucket
NAME          TYPE                                DATA   AGE
test-bucket   connection.crossplane.io/v1alpha1   3      6m31s
> kubectl get secrets/test-bucket --template={{.data.arn}} | base64 -D
arn:aws:s3:::demo-bucket-e34cs
> kubectl get secrets/test-bucket --template={{.data.id}} | base64 -D
demo-bucket-e34cs
> kubectl get secrets/test-bucket --template={{.data.region}} | base64 -D
us-east-1
```
> add bucket id,arn and regio to writeConnectionSecretToRef

- apis/eks/v1beta1/zz_generated_terraformed.go
- config/eks/config.go
I want to address the issue described in #976:
ReleaseVersion must not be synced back into the `Kind=NodeGroup` resource,
this is a invalid configuration when using a custom AMI. AWS Error:
```
InvalidParameterException: You cannot specify the field releaseVersion when using custom AMIs.
```
Fixes #976
I have:
Built a image off my PR and deployed it into a cluster.
I was able to successfully create a EKS NodeGroup with a custom AMI. I also was able to update it a couple of times. This previously failed with the error mentioned in #976.
> fix: allow using custom AMI

- Makefile
Fixes #
I have:
It looks like bumping the `golangci-lint` version to the latest did not resolve the OOM issue. But we still decided to bump our dependency and we will probably do a memory profiling to understand what's causing the memory surge in the linter.
> Bump golangci-lint to v1.55.2

- config/docdb/config.go
Added the Docdb cluster endpoint and arn to the connection details so that the value will appear in the secret created by writeConnectionSecretToRef
Fixes #
I have:
manually:
```
> kubectl get secrets/my-docdb
NAME       TYPE                                DATA   AGE
my-docdb   connection.crossplane.io/v1alpha1   3      6m1s
> kubectl get secrets/my-docdb --template={{.data.endpoint}} | base64 -D                                                                             
docdb-demo-lnj42.cluster-c3kmasxmrnwp.eu-west-1.docdb.amazonaws.com
> kubectl get secrets/my-docdb --template={{.data.arn}} | base64 -D                                                                           
arn:aws:rds:eu-west-2:<account-id>:cluster:docdb-demo-lnj42
```
> added endpoint and arn to docdb cluster secret

- config/externalname.go
- examples/ec2/transitgatewayvpcattachmentaccepter.yaml
Fix external name configuration of TransitGatewayVPCAttachmentAccepter resource
Fixes #816 
I have:
Tested locally. The issue was reproduced by following the steps in the description of #816. Then after applying the proposed fix in this PR, the issue was resolved.
Uptest: https://github.com/upbound/provider-aws/actions/runs/6980792906
> Fix external name configuration of TransitGatewayVPCAttachmentAccepter resource

- apis/iam/v1beta1/zz_generated_terraformed.go
- config/iam/config.go
Signed-off-by: Christopher Haar <christopher.haar@upbound.io>
(cherry picked from commit 765c9502c23b064e0ed9afce049f9718fe0962a9)
Partially fixes: https://github.com/upbound/provider-aws/issues/944
I have:
Uptest: https://github.com/upbound/provider-aws/actions/runs/7030730632
> [release-0.42] Backport #933

- go.mod
- internal/clients/aws.go
Adds support for custom endpoint configuration of new architecture external clients. Before this change, custom endpoint configurations were rejected, due to similar implementation with old architecture. However, this limitation is no longer valid for new provider architecture.
Fixes #971 
I have:
> add support for endpoint configuration of no-fork external client

- apis/lambda/v1beta1/zz_generated_terraformed.go
- config/lambda/config.go
- examples/lambda/permission.yaml
- fix statement_id_prefix
- add working example
Fixes #1001
I have:
Uptest: https://github.com/upbound/provider-aws/actions/runs/7091214720
> fix(late-init): Lambda Permission: statement_id_prefix late initialization problem

- go.mod
- internal/clients/aws.go
Handles `assumeRoleChain` config with chain length greater than 1, in the AWS provider config. Native terraform provider config block cannot handle this (see https://github.com/hashicorp/terraform-provider-aws/issues/22728), therefore the AssumeRole STS operations are handled in provider code and obtained AWS STS temporary credentials are used.
Fixes #998
I have:
Tested with an AWS ProviderConfig specifying AssumeRoleChain of 3, with cross-account roles assuming each other. A VPC object is successfully created using this provider config.
> handle assumeRoleChain config with length > 1 in no-fork clients

- config/externalname.go
- internal/controller/appconfig/environment/zz_controller.go
`aws_appconfig_environment` is a [terraform-plugin-sdk](https://github.com/hashicorp/terraform-plugin-sdk) resource which we are currently reconciling using the CLI-based reconciler. This PR changes its external client to [`controller.noForkAsyncExternal`](https://github.com/crossplane/upjet/blob/807fb9dd9553ae41106c8c083d374af8c98ee45a/pkg/controller/external_async_nofork.go#L99) so that it's reconciled under the new architecture.
I have:
Via uptest: https://github.com/upbound/provider-aws/actions/runs/7291718665
> Reconcile aws_appconfig_environment using the TF SDK-based external client

- Makefile
Relevant PR: #1037 
This PR bumps `crddiff` to `v0.8.0` and adds the `--enable-upjet-extensions` command-line option while running it. Please see the description in https://github.com/upbound/uptest/pull/160 for more details.
I have:
> Bump crddiff to v0.8.0

- examples/sns/topic-fifo.yaml
Added an example for fifo SNS topics, which have some specific naming restrictions.
Fixes #670
I have:
(I don't think this is necessary anymore, as everything in `make reviewable test` is run in CI (lint, unit tests, check-diff)
I ran uptest locally, and will run it again on the PR. 
No changes to the actual provider code, just an added example/test case.
> Add examples for fifo SNS topics

- internal/clients/aws.go
Fixes #1054 
The Terraform provider schema declares `assume_role_with_web_identity` as a [list](https://github.com/hashicorp/terraform-provider-aws/blob/7aea0db5fac1691f3528e89a483424ae310b18dc/internal/provider/provider.go#L672), whereas we prepare a [map](https://github.com/upbound/provider-aws/blob/8f8e547a8fbba3cac6e3b1ffe137478818b4b06e/internal/clients/aws.go#L133). The theory is that `sts.AssumeRoleWithWebIdentity` is thus not configured properly for the no-fork external client and as a last resort, the provider tries to access the IMDS to authenticate its requests. This PR changes the configuration value from a map to a list as expected by the corresponding Terraform provider schema.
I have:
TODO:
> Make `assume_role_with_web_identity` provider configuration value a list

- config/externalname.go
- examples/cognitoidp/userpoolclient-with-dashes.yaml
- examples/cognitoidp/userpoolclient.yaml
- examples/cognitoidp/userpooluicustomization.yaml
The cognito idp user pool client is one of the handful of resources in terraform-provider-aws v4.67.0 that use the terraform plugin framework, and therefore that we still reconcile by forking a CLI terraform process. 
There are three problems with the cognito user pool client:
1. Creation fails if the `spec.forProvider.name` doesn't match the regex for the `clientId`
2. Whenever the provider pod restarts, crossplane will either create a duplicate resource, orphaning the existing one, or get into a Synced: False state, depending on whether `spec.forProvider.name` matches the `clientId` regex. 
3. Observe-only resources fail, because `terraform import` expects an argument that is not the same as the terraform id. 
This PR fixes the first two issues, and makes the third issue no worse. 
This …
> (bugfix) Fix cognito user pool client orphaned resources

- .github/renovate.json5
- automatic PRs for up version upgrades
- automatic PRs for kind version upgrades
- automatic PRs for uptest version upgrades
- automatic PRs for golangcilint version upgrades
Fixes #
I have:
local dry-run
```
RENOVATE_CONFIG_FILE=.github/renovate.json5 \
npx renovate \
--token=$GITHUB_TOKEN \
--schedule="" \
--dry-run=full \
upbound/provider-aws
```
```
[...]
INFO: Dependency extraction complete (repository=upbound/provider-aws, baseBranch=main)
"stats": {
"managers": {
"dockerfile": {"fileCount": 1, "depCount": 2},
"github-actions": {"fileCount": 11, "depCount": 23},
"gomod": {"fileCount": 1, "depCount": 205},
"regex": {"fileCount": 3, "depCount": 3}
},
"total": {"fileCount": 16, "depCount": 233}
}
[...]
INFO: DRY-RUN: Would commit files to branch renovate/kubernetes-sigs-kind-0.x …
```
> feat(renovate): add uptest, up and golangcilint for renovate pr

- apis/docdb/v1beta1/zz_cluster_types.go
- apis/docdb/v1beta1/zz_generated.deepcopy.go
- apis/docdb/v1beta1/zz_generated.resolvers.go
- config/docdb/config.go
- examples/docdb/cluster.yaml
- package/crds/docdb.aws.upbound.io_clusters.yaml
Add `dbClusterParameterGroupNameSelector` to DocDB Cluster
* Add reference configuration
* Add generated files
* Extend uptest example
I have:
uptest below
> DocDB: add `dbClusterParameterGroupName` Selector for Cluster

- internal/clients/aws.go
Fixes #1063 
The Terraform provider schema declares `endpoints` as a [single element set of key-value map](https://github.com/hashicorp/terraform-provider-aws/blob/7aea0db5fac1691f3528e89a483424ae310b18dc/internal/provider/provider.go#L741), whereas we prepare a [key-value map](https://github.com/upbound/provider-aws/blob/8f8e547a8fbba3cac6e3b1ffe137478818b4b06e/internal/clients/aws.go#L196) in the TF provider configuration block. 
This was being properly handled by terraform CLI based external clients, and no-fork clients that used to configure AWS client directly (`0.44.0` and `0.45.0`). 
Starting from `0.46.0` we switched to [native provider's `Configure` method](https://github.com/upbound/provider-aws/blob/8f8e547a8fbba3cac6e3b1ffe137478818b4b06e/internal/clients/aws.go#L225), which …
> Make endpoints provider configuration value single-element list

- config/docdb/config.go
- examples/docdb/cluster.yaml
* Add `master_password` to Cluster connection secret as `password` field
* Extend uptest example
* Fixes #1077
I have:
```
k apply -f examples/docdb/cluster.yaml
k get managed
NAME                                                 READY   SYNCED   EXTERNAL-NAME   AGE
clusterparametergroup.docdb.aws.upbound.io/example   True    True     example         10m
NAME                                            READY   SYNCED   EXTERNAL-NAME      AGE
cluster.docdb.aws.upbound.io/my-docdb-cluster   True    True     my-docdb-cluster   10m
k get secret -A
...
upbound-system   docdb-cluster-secret                              connection.crossplane.io/v1alpha1   4      3m27s
k view-secret -n upbound-system docdb-cluster-secret
Multiple sub keys found. Specify another argument, one of:
-> arn
-> …
```
> [docdb]: add master_password to Cluster connection secret

- examples/rds/clusteractivitystream.yaml
- examples/rds/clusterendpoint.yaml
- examples/rds/clusterparametergroup.yaml
- examples/rds/clusterroleassociation.yaml
- examples/rds/clustersnapshot.yaml
- examples/rds/dbinstanceautomatedbackupsreplication.yaml
- examples/rds/dbsnapshotcopy.yaml
- examples/rds/instanceroleassociation.yaml
- examples/rds/snapshot.yaml
This PR fixes example manifests and makes them uptestable for the following resources in `rds` group:
- `Snapshot`
- `InstanceRoleAssociation`
- `ClusterRoleAssociation`
- `ClusterActivityStream`
- `ClusterEndpoint`
- `ClusterParameterGroup`
- `ClusterSnapshot`
- `DBInstanceAutomatedBackupsReplication`
- `DBSnapshotCopy`
Tested with uptest in comments below.
> Improve example manifests for rds group

- Makefile
Since we started consuming https://github.com/upbound/uptest/pull/169, running `make uptest` or `make e2e` locally fails on the import step unless the CROSSPLANE_NAMESPACE env var is defined. This sets it in the uptest makefile step.
It would be great to backport this to at least 0.47, just to make local development on that branch easier, but I don't think I have permission to add the appropriate label.
I have:
Running uptest locally now passes without any additional env vars set.
> Expose CROSSPLANE_NAMESPACE to uptest

- apis/docdb/v1beta1/zz_cluster_types.go
- apis/docdb/v1beta1/zz_generated.deepcopy.go
- config/common/common.go
- config/common/common_test.go
- config/docdb/config.go
- config/rds/config.go
- examples/docdb/v1beta1/cluster.yaml
- package/crds/docdb.aws.upbound.io_clusters.yaml
* Move `PasswordGenerator` function to common location
* Enable `autoGeneratePassword` to docdb `Cluster`
* Fixes https://github.com/upbound/provider-aws/issues/1105
I have:
```
k get -f examples/docdb/cluster.yaml
NAME                                            READY   SYNCED   EXTERNAL-NAME      AGE
cluster.docdb.aws.upbound.io/my-docdb-cluster   True    True     my-docdb-cluster   3m11s
NAME                                                 READY   SYNCED   EXTERNAL-NAME   AGE
clusterparametergroup.docdb.aws.upbound.io/example   True    True     example         3m11s
k view-secret -n upbound-system docdb-creds
Choosing key: password
yQgj05GTSj0d9HDodzRZDMcmB2B%
k view-secret -n upbound-system docdb-cluster-secret password
yQgj05GTSj0d9HDodzRZDMcmB2B%
```
> [docdb]: Add autoGeneratePassword capability to Cluster

- examples/elasticache/v1beta1/replicationgroup-engineVersion.yaml
- go.mod
- go.sum
This PR adds a new example manifest for the `ReplicationGroup.elasticache` resource with an explicit `engineVersion` as a regression test for #1071. We keep the original example manifest, which does not mention an explicit engine version, and thus requires less maintenance on our side (e.g., when the explicitly referenced engine version is no longer available).
I have:
Via uptest runs:
- Manifest with engine version: https://github.com/upbound/provider-aws/actions/runs/7730125050
- Generic manifest: https://github.com/upbound/provider-aws/actions/runs/7730127617
> Add an example manifest for ReplicationGroup.elasticache with "engineVersion"

- config/secretsmanager/config.go
- examples/secretsmanager/v1beta1/secret-withreplica.yaml
Configures a custom diff function for `replica` field in `Secret/secretmanagers.aws` resource, with a special set difference implementation.
The `replica` attribute has `Set` type in the resource schema, which consists of elements with `region` and `kms_key_id` attributes. The `kms_key_id` is an optional + computed field, meaning that user can set a kms_key_id or if they don't, the cloud API will assign an automatic kms_key_id.
Terraform SDK has a limitation that set elements with optional+computed fields always show perma-diff, because of the Set representation and hashing logic. 
- Set diffs are calculated as a whole, by comparing the hash list of elements. Therefore, it never captures individual element field change diffs. As a result of that, changes in sets always result in removal …
> fix Secret/secretmanagers.aws update loop for replica field

- Makefile
This PR adds the `--certs-dir=""` option to the provider command in `make run` so that the conversion webhooks are disabled in local tests.
I have:
Locally tested.
> Add --certs-dir="" option to the provider command to prevent the conversion webhooks in "make run"

- config/secretsmanager/config.go
- examples/secretsmanager/v1beta1/secret-withreplica.yaml
- examples/secretsmanager/v1beta1/secret.yaml
Fixes the custom diff logic (introduced at https://github.com/upbound/provider-aws/pull/1107) for `replica` attribute when it is not specified in the config and the diff does not involve `replica` field. The custom diff function is triggered for any update diff, and the current logic tries to read the `replica` field unconditionally. When `replica` is not specified in config, the get operation fails the whole custom diff function, therefore the Observe operation.
This change fixes the custom diff logic by: 
- early exit with no error when there is no change/diff involved for `replica`. We only need to change
- early exit with no error if `replica` attibute is not specified in the MR spec. This is already handled properly by the regular diff and needs no customization.
Fixes #1128 
I have: …
> fix Secret/secretmanager.aws custom diff logic when replica config is empty

- config/secretsmanager/config.go
- examples/secretsmanager/secret-withreplica.yaml
- examples/secretsmanager/secret.yaml
Backport of #1107 and #1144 to `release-0.47`.
Tests:
- secretsmanager.Secret
- https://github.com/upbound/provider-aws/actions/runs/7917258418
- https://github.com/upbound/provider-aws/actions/runs/7917600558
> [Backport release-0.47] fix Secret/secretmanagers.aws update loop for replica field and custom diff logic when replica config is empty

- internal/clients/aws.go
Backport of #1066 to `release-0.47`.
Uptest Run: https://github.com/upbound/provider-aws/actions/runs/7929858398
> [Backport release-0.47] Make endpoint provider configuration value single-element list

- .github/workflows/ci.yml
Relevant PR: https://github.com/upbound/uptest/pull/188
This PR enables the disk clean-up step in the CI workflow to fix the failing `check-diff`, `unit-tests` & `local-deploy` jobs in this branch. For more context, please refer to https://github.com/upbound/uptest/pull/188. Please also see this [comment](https://github.com/upbound/provider-aws/pull/1195#issuecomment-1982866839).
I have:
Via the job run [here](https://github.com/upbound/provider-aws/actions/runs/8186204677/job/22384138959?pr=1197) and [here](https://github.com/upbound/provider-aws/actions/runs/8186846228/).
> Reclaim disk space in an initial step while running the CI jobs

- .github/workflows/backport.yml
- .github/workflows/ci.yml
- .github/workflows/commands.yml
- .github/workflows/e2e.yaml
- .github/workflows/issue-triage.yml
- .github/workflows/native-provider-bump.yml
- .github/workflows/publish-service-artifacts.yml
- .github/workflows/scan.yml
- .github/workflows/tag.yaml
- .github/workflows/updoc.yml
Relevant PR: https://github.com/upbound/uptest/pull/184
This PR replaces the larger runners we are using for the:
- `e2e`, `publish-service-artifacts` workflows
- `lint`, `publish-artifacts` jobs
to the standard `ubuntu-22.04` workflow runners. This will also allow us to check whether any CI jobs need larger runners in this repo.
Unfortunately, the `e2e` workflow (`uptest`) running on the standard runner cannot be tested with this PR. I'm planning to test the `e2e` workflow on a separate repository. We have switched to the family providers in `uptest` runs, so I hope there's no need for the larger runners for `uptest` runs. This also depends on the time given to the `e2e` workflow and the resource providers needed to run a test.
Another test we need to do is the …
> Consume the reusable workflows from upbound/uptest@standard-runners

- .github/workflows/publish-service-artifacts.yml
Relevant PR: https://github.com/upbound/uptest/pull/192
The failing run for the `publish-service-artifacts` CI job [here](https://github.com/upbound/provider-aws/actions/runs/8249459854/job/22561895636) reveals that we may be able to benefit from disk cleaning for this job:
This PR adds the `Cleanup Disk` step for the child jobs of the `publish-service-artifact` job, which are responsible for building the family packages and pushing them to the registry,
I have:
A test run of the job is [here](https://github.com/upbound/provider-aws/actions/runs/8251132666/job/22567470843):
Please note the newly introduced `Cleanup Disk` step for the child builder jobs.
Another successful run is here: https://github.com/upbound/provider-aws/actions/runs/8251670678
> Run the "Cleanup Disk" step in the publish-service-artifacts CI job

- .github/workflows/ci.yml
- .golangci.yml
- Makefile
This PR adds a `Disk Cleanup` step as the first step in the `lint` CI job to allow for more virtual memory space during linting and limits the concurrency of both of the first analysis cache construction and the second full linting phases to 3. Previously, the second phase was run with the max available concurrency as we had observed no issues with the standard Github hosted runners (label `ubuntu-22.04`) but in a [test PR](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1210), we had some mixed results with this phase. So we will try configuring the second phase by limiting its concurrency. Please see [this comment](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1210#issuecomment-1994372493) for some further details.
Furthermore, the first phase is now always …
> Add a "Disk Cleanup" step as the first step in the lint job

- examples/iam/v1beta1/user.yaml
remove spec.forProvider.name for iam policy examples
```
└─ CompositePostgreSQLInstance/my-db-aws-gb9qt      False    True    ReconcileError: ...nd=Policy): .spec.forProvider.name: field not declared in schema   
```
marketplace link: https://marketplace.upbound.io/providers/upbound/provider-aws-iam/v1.2.0/resources/iam.aws.upbound.io/Policy/v1beta1#doc:spec-forProvider
Fixes #
I have:
> fix(example): remove spec.forProvider.name for iam policy examples

- internal/clients/aws.go
Fixes #1220 
#1204 removed obsolete TF-CLI related configuration codepath and switched to native TF SDK configuration.
As a result of native SDK configuration, `terraform.Setup.Configuration` was no longer needed to configure TF AWS client and we cease
However, several external name configurations which use external name templates, still rely on `terraform.Setup.Configuration` map to obtain `region` value. 
The change adds the `region` parameter back to `terraform.Setup.Configuration`.
I have:
With uptest, create resources that uses ` .setup.configuration` in their external name configs
> Add region parameter back to TF setup.Configuration

- cmd/provider/monolith/zz_main.go
- hack/main.go.tmpl
- package/crossplane.yaml.tmpl
As we are approaching the end of support for the monolithic AWS package, this PR introduces:
- Info logs in the monolithic provider's output that communicate the deprecation and the next steps.
- A deprecation message in the monolithic packages marketplace listing.
- No deprecation message in a resource provider's marketplace listing.
I have:
> Log a deprecation message when the monolithic provider is run

- AUTHENTICATION.md
This PR updates authentication document for `WebIdentity`
I have:
> Update authentication document for WebIdentity

- go.mod
- go.sum
- internal/clients/aws.go
- internal/clients/provider_config.go
This PR introduces three AWS API call counters:
1. An AWS SDK v2 [middleware](https://aws.github.io/aws-sdk-go-v2/docs/middleware/) to count authentication calls,
2. An AWS SDK v2 middleware to count resource API calls,
3. An AWS SDK v1 [session handler](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#hdr-Adding_Handlers) to count resource API calls.
API calls that couldn't be completed because of a connection error are not counted. API calls that return API errors (or no errors) are counted. There are no comprehensive AWS documentation on request rate limits, but here are two resources on the topic, for reference:
1. [Request throttling for the Amazon EC2 API](https://docs.aws.amazon.com/ec2/latest/devguide/ec2-api-throttling.html)
2. [Managing and monitoring API throttling in …
> Count external API calls

- internal/clients/creds_cache.go
The provider cache manager currently uses `ProviderConfig.ResourceVersion` when computing the cache keys. This PR changes it to `ProviderConfig.Generation` so that only ProviderConfig's `spec` updates will invalidate cache entries.
I have:
Validated the PR using the package `index.docker.io/ulucinar/provider-aws-iam:v1.3.0-8dbbc58fbd82da76ef5f8f50c34aa75494964bbd` and by modifying the `spec` of the `ProviderConfig`. Also via uptest here: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/8470828375
> Use Generation instead of ResourceVersion when computing the cache key

- package/auth.yaml
Update `auth.yaml` to select specific fields in the spec to support Upbound as an identity provider.
Screenshot of a deploy with a new xpkg:
Fixes https://github.com/upbound/upbound-frontend/issues/3751
I have:
> Select spec fields specific to Upbound OIDC

- .github/workflows/backport.yml
- .github/workflows/ci.yml
- .github/workflows/commands.yml
- .github/workflows/e2e.yaml
- .github/workflows/native-provider-bump.yml
- .github/workflows/publish-service-artifacts.yml
- .github/workflows/scan.yml
- .github/workflows/tag.yaml
- .github/workflows/updoc.yml
All the CI jobs have started failing. 
Github actions doesn't follow github repository redirects when resolving reusable workflows, as documented [here](https://docs.github.com/en/actions/using-workflows/reusing-workflows#access-to-reusable-workflows).
The `upbound/uptest` repo has been renamed to `upbound/official-providers-ci`.
> Rename upbound provider ci repo

- apis/lambda/v1beta1/zz_function_terraformed.go
- apis/lambda/v1beta1/zz_function_types.go
- config/lambda/config.go
- examples/lambda/v1beta1/function.yaml
- package/crds/lambda.aws.upbound.io_functions.yaml
This PR fixes the update loop in the `Function.lambda` resource.
Fixes: https://github.com/crossplane-contrib/provider-upjet-aws/issues/1027
I have:
- Create a `Repository.ecr` resource by applying the following:
```
apiVersion: ecr.aws.upbound.io/v1beta1
kind: Repository
metadata:
name: test-repo
spec:
forProvider:
region: us-east-1
imageTagMutability: "IMMUTABLE"
```
- Push an image to the repository:
- Retrieve an authentication token and authenticate your Docker client to your registry. Use the AWS CLI: `aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account_id>.dkr.ecr.us-east-1.amazonaws.com`
- Build your Docker image using the following command. For information on building a Docker file from scratch see the instructions [here …
> Fix update loop for Function.lambda resource 

- Makefile
Code generation depends on JSON schema of terraform-provider-aws ([`config/schema.json`](https://github.com/crossplane-contrib/provider-upjet-aws/blob/fd908a63f7d81b5039c1639b5082fcc6fa84017c/config/schema.json)). [Converting a Terraform provider's schema to JSON](https://developer.hashicorp.com/terraform/cli/v1.5.x/commands/providers/schema#json) is performed by Terraform CLI, which requires a provider binary. Therefore, when we introduce a new resource, such as [MQ User](https://github.com/upbound/terraform-provider-aws/pull/236), to [our fork of terraform-provider-aws](https://github.com/upbound/terraform-provider-aws), we also [release the provider as binary](https://github.com/upbound/terraform-provider-aws/releases). This PR introduces necessary changes to download custom provider …
> Use custom Terraform provider release to generate schema.json

- AUTHENTICATION.md
- docs/family/Configuration.md
* Replace deprecate `ControllerConfig`-based example with `DeploymentRuntimeConfig` instructions to set IRSA annotation on Provider ServiceAccount
* Occasional whitespace busting
I have:
By applying documented manifests and checking that the annotation was propagated to the provider serviceaccount
```
k get -f examples/deploymentruntimeconfigs/irsa-drc.yaml  -o yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"pkg.crossplane.io/v1beta1","kind":"DeploymentRuntimeConfig","metadata":{"annotations":{},"name":"irsa-drc"},"spec":{"serviceAccountTemplate":{"metadata":{"annotations":{"eks.amazonaws.com/role-arn":"arn:aws:iam::111122223333:role/iam-role-name"}}}}}
creationTimestamp: …
```
> Auth doc: update IRSA example with `DeploymentRuntimeConfig`

- .github/workflows/ci.yml
- .golangci.yml
While [bumping the underlying Terraform provider version](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1315), we've observed failing linter runs. This is probably caused by the changing dependencies and the invalidation of the linter cache. We had previously observed a similar situation when working with the linter in the `release-0.47` branch, and we had applied more aggressive parameters in #1217. This PR copies some of those parameters to the `main` branch.
I have:
Via `make lint` runs and in #1217.
> Reduce linter concurrency to 1

- apis/rds/v1beta1/zz_clusterinstance_terraformed.go
- config/rds/config.go
- examples/rds/v1beta1/clusterinstance.yaml
- fix a few late init problems with rds clusterinstance
After upgrading the Version in the Cluster the ClusterInstance gets stuck in an update-loop because of the `engineVersion`
`spec.forProvider.engineVersion`
```
2024-05-15T14:49:54Z    DEBUG    provider-aws    Diff detected    {"uid": "31f30f84-59ed-4720-ad3a-93aae50eb27d", "name": "xxx", "gvk": "rds.aws.upbound.io/v1beta1, Kind=ClusterInstance", "instanceDiff": "*terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{\"engine_version\":*terraform.ResourceAttrDiff{Old:\"15.5\", New:\"15.4\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, RawConfig:cty.NilVal, …
```
> fix(rds): fix late init for rds clusterinstance

- apis/s3/v1beta1/zz_bucketlifecycleconfiguration_types.go
- config/s3/config.go
- package/crds/s3.aws.upbound.io_bucketlifecycleconfigurations.yaml
This PR fixes the documentation of [`rule.filter.prefix`](https://marketplace.upbound.io/providers/upbound/provider-aws-s3/v1.5.0/resources/s3.aws.upbound.io/BucketLifecycleConfiguration/v1beta1#doc:spec-forProvider-rule-filter-prefix) and [`rule.filter.and.prefix`](https://marketplace.upbound.io/providers/upbound/provider-aws-s3/v1.5.0/resources/s3.aws.upbound.io/BucketLifecycleConfiguration/v1beta1#doc:spec-forProvider-rule-filter-and-prefix) fields for `BucketLifecycleConfiguration.s3`.
The field that will be deprecated is the [`rule.prefix`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration#prefix) argument, somehow the document was generated incorrectly for `rule.filter.prefix` and `rule.filter.and.prefix` arguments.
Fixes: …
> Fix documentation of `rule.filter.prefix` field for `BucketLifecycleConfiguration.s3`

- apis/elasticache/v1beta2/zz_generated.deepcopy.go
- apis/elasticache/v1beta2/zz_replicationgroup_types.go
- config/elasticache/config.go
- examples/elasticache/v1beta2/replicationgroup.yaml
- package/crds/elasticache.aws.upbound.io_replicationgroups.yaml
- Add option autoGenerateAuthToken for ElastiCache ReplicationGroup
- Add port/endpoint connection details for ElastiCache ReplicationGroup
Fixes #1102
I have:
Uptest run: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9397299773
> ElastiCache ReplicationGroup auth token generation and connection details

- config/sns/config.go
- examples/sns/v1beta1/topic-with-policy.yaml
- go.mod
We've observed update loops with the `Topic.sns` resources when inline policies are given. The desired policy document in the `spec` can differ from the actual (observed) document in the following two ways:
- Missing `Version` node. An example is as follows:
```json
{
"Statement": [
{
"Sid": "publish",
"Effect": "Allow",
"Principal": {
"AWS": "arn:aws:iam::123456789110:role/sample-role"
},
"Action": "sns:Publish",
"Resource": "arn:aws:sns:us-west-1:123456789110:resource1"
},
{
"Sid": "get-attributes",
"Effect": "Allow",
"Principal": {
"AWS": "arn:aws:iam::123456789110:role/sample-role"
},
"Action": "sns:GetTopicAttributes",
"Resource": "arn:aws:sns:us-west-1:123456789110:resource1"
},
{
"Sid": "list-subscriptions",
"Effect": "Allow",
"Principal": {
"AWS": …
```
> Fix Topic.sns update loops

- apis/eks/v1beta1/clusterauth_types.go
- package/crds/eks.aws.upbound.io_clusterauths.yaml
There was a recent change in upjet that swapped the order of the Ready and Synced columns in the generated managed resource CRDs. That's already been merged and released in provider-upjet-aws. However, we forgot about ClusterAuth.eks, which is the only (I think?) CRD that's not generated by upjet. 
The result is that currently when listing managed resources, for all MR kinds other than ClusterAuth, Synced appears before Ready, but for ClusterAuth, Ready appears before synced.
This PR fixes that.
I have:
Using [uptest](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/9414897033) on this PR and manually:
```
NAME                                  SYNCED   READY   EXTERNAL-NAME   AGE
clusterauth.eks.aws.upbound.io/auth   True     True    auth            10m
``` …
> re-order columns for handwritten ClusterAuth.eks

- apis/eks/v1beta2/zz_nodegroup_terraformed.go
- config/eks/config.go
- examples/eks/v1beta2/cluster.yaml
This is a followup to PR https://github.com/crossplane-contrib/provider-upjet-aws/pull/977, and adds the version field. 
I've also changed one of the test subnets to AZ us-west-1c, as some accounts don't get access to 1a
```shell
aws ec2 describe-availability-zones --region us-west-1 
{
"AvailabilityZones": [
{
"State": "available",
"OptInStatus": "opt-in-not-required",
"Messages": [],
"RegionName": "us-west-1",
"ZoneName": "us-west-1b",
"ZoneId": "usw1-az3",
"GroupName": "us-west-1",
"NetworkBorderGroup": "us-west-1",
"ZoneType": "availability-zone"
},
{
"State": "available",
"OptInStatus": "opt-in-not-required",
"Messages": [],
"RegionName": "us-west-1",
"ZoneName": "us-west-1c",
"ZoneId": "usw1-az1",
"GroupName": "us-west-1",
"NetworkBorderGroup": "us-west-1",
"ZoneType": …
```
> lateinit version due to nodegroup conflict

- apis/ec2/v1beta2/zz_launchtemplate_terraformed.go
- config/ec2/config.go
- examples/ec2/v1beta1/launchtemplate.yaml
fix update loop issue in ec2 launchtemplate when using `spec.forProvider.updateDefaultVersion: true` we need to skip late init for defaultVersion otherwise the manifest looks like:
```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: LaunchTemplate
[...]
spec:
deletionPolicy: Delete
forProvider:
[...]
defaultVersion: 1
[...]
updateDefaultVersion: true
[...]
status:
atProvider:
[...]
defaultVersion: 7
[...]
latestVersion: 7
[...]
conditions:
- lastTransitionTime: "2024-06-05T14:17:20Z"
reason: Available
status: "True"
type: Ready
- lastTransitionTime: "2024-06-05T17:59:25Z"
reason: ReconcilePaused
status: "False"
type: Synced
- lastTransitionTime: "2024-06-05T14:17:18Z"
reason: Success
status: "True"
type: LastAsyncOperation
```
Fixes #
I have:
Uptest run: …
> fix(ec2): launchtemplate late init remove for defaultVersion 

- apis/ec2/v1beta1/zz_launchtemplate_terraformed.go
- apis/eks/v1beta1/zz_nodegroup_terraformed.go
followup for https://github.com/crossplane-contrib/provider-upjet-aws/pull/1374 and https://github.com/crossplane-contrib/provider-upjet-aws/pull/1377
@ulucinar in chat: `upjet currently does not generate the older versions, it generates only the latest version. We need to manually maintain the older versions.`
Fixes #1415
I have:
Uptest: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/10074958060
> fix(late-init): add late-init skips for v1beta1

- config/opensearch/config.go
- examples/opensearch/v1beta1/domain.yaml
- examples/opensearch/v1beta2/domain.yaml
Implements https://github.com/crossplane-contrib/provider-upjet-aws/issues/1442
I have:
I ran a make uptest on my own AWS EKS cluster on the example that was modified as part of this PR, and the cluster address was properly printed.
> feat(opensearch): connection details for opensearch

- apis/v1beta1/types.go
- examples/providerconfig/v1beta1/pod-identity-providerconfig.yaml
- internal/clients/provider_config.go
- package/crds/aws.upbound.io_providerconfigs.yaml
- add new `spec.credentials.source` PodIdentity
- implemented a test environment based on: https://github.com/upbound/configuration-aws-eks here: https://github.com/haarchri/configuration-aws-eks-uxp-podidentity which added a UXP Release, Provider IAM Role, Pod Identity and a DeploymentRuntimeConfig https://github.com/haarchri/configuration-aws-eks-uxp-podidentity/blob/main/apis/pat/composition.yaml#L430-L526
Fixes #1249 #1254 #1308 #1252
I have:
spin up a Network + EKS Cluster:
```
kubectl apply -f examples/pat/network-xr.yaml
kubectl apply -f examples/pat/eks-xr.yaml
```
connect to your EKS Cluster:
```
aws sso login --profile login
aws eks update-kubeconfig --region us-west-2 --name  configuration-aws-eks-v2lbr --profile AdministratorAccess-12345678910
```
apply the following …
> feat(pod-identity): add option for pod-identity

- examples/ec2/v1beta1/fleet.yaml
Updated the `ec2_fleet` example to use the more recent `v1beta2` companion `ec2_launch_template`. Additionally fixed some formatting issues in the example that had caused some 'missing property' warnings.
I have:
uptest
```
export UPTEST_EXAMPLE_LIST=examples/ec2/v1beta1/fleet.yaml
make e2e
```
Result:
```
--- PASS: kuttl (72.98s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/case (72.20s)
```
> Update EC2 Fleet example to use most recent LaunchTemplate version

- apis/eks/v1beta1/zz_nodegroup_terraformed.go
- apis/eks/v1beta2/zz_nodegroup_terraformed.go
- config/eks/config.go
Ignores late initialize for `scaling_config` field in `NodeGroup.eks` resource.
Fixes https://github.com/crossplane-contrib/provider-upjet-aws/issues/1469
I have:
Manually tested with `index.docker.io/turkenf/provider-aws:v1.13.0-rc.0.1.gf7fd1d8ba`
> Ignore late initialize for scaling_config in NodeGroup resource

- cluster/images/provider-aws/Makefile
Adds `cleanupexamples` tool to subpackages build process
I have:
Manually tested with `make build.all publish BRANCH_NAME=main` command in local provider-upjet-aws.
Created and controlled image `index.docker.io/turkenf/provider-aws:v1.14.0-rc.0.11.gda1945136`
> Add cleanupexamples tool to subpackages build process

- Makefile
- cluster/images/provider-aws/Makefile
- package/crossplane.yaml.tmpl
This PR introduces a change for parametrizing the auth group and config group overrides. uses different parameters name for auth and config group overrides. There is not a behavior change for the provider because the values are set to the same (PROVIDER_NAME). Now, the dependency between these fields were eliminated.
I have:
Tested locally.
> Use different parameters name for auth and config group overrides

- Makefile
- config/elbv2/config.go
- examples/elbv2/v1beta2/lblistener-forward-multiple-targetgroups.yaml
- examples/elbv2/v1beta2/lblistener-forward-single-targetgroup.yaml
- go.mod
- go.sum
Fixes the update loop for LBListener.
Will fix #1352 
I have:
manual
> add custom diff for LBListener forward options

- apis/rds/v1beta1/zz_cluster_types.go
- apis/rds/v1beta1/zz_generated.resolvers.go
- apis/rds/v1beta2/zz_cluster_types.go
- apis/rds/v1beta2/zz_generated.resolvers.go
- config/rds/config.go
- examples/rds/v1beta1/cluster-with-kmskey.yaml
Adds the `PathARNExtractor` for `kms_key_id` to the rds cluster resource
Fixes: https://github.com/crossplane-contrib/provider-upjet-aws/issues/1523
I have:
Tested with uptest (https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/11456655642) and manually:
```
conditions:
- lastTransitionTime: "2024-10-22T08:42:00Z"
reason: ReconcileSuccess
status: "True"
type: Synced
- lastTransitionTime: "2024-10-22T08:42:55Z"
reason: Available
status: "True"
type: Ready
- lastTransitionTime: "2024-10-22T08:42:53Z"
reason: Success
status: "True"
type: LastAsyncOperation
- lastTransitionTime: "2024-10-22T08:44:24Z"
reason: UpToDate
status: "True"
type: Test
```
> Add PathARNExtractor for kms_key_id to rds cluster

- config/opensearch/config.go
- examples/opensearch/v1beta1/domain-with-advanced-security-options.yaml
Fixes the custom diff function for `Domain.opensearch` resource, which ignored valid diffs for `advanced_security_options.#`, therefore configuring these options were not propagated to the external resource.
Fixes #1531 
I have:
Manually and [uptest](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/11456404274)
> fix custom diff for Domain.opensearch ignoring valid diff

- .golangci.yml
- Makefile
Update crossplane/build to [d3155548bfab68fc8bea64c5526642b7b565ae33](https://github.com/crossplane/build/commit/d3155548bfab68fc8bea64c5526642b7b565ae33) which includes an update of `golangci-lint` to `1.61.0` to fix problems linting on macOS (arm64). See https://github.com/crossplane/build/pull/23
Also includes the following deprecation fixes:
- Update `.golangci.yml` config for several deprecated config settings
- Removed archived/deprecated linter `interfacer`
- Replaced `megacheck` with `gosimple`, `staticcheck`, and `unused`
I have:
CI & `make lint` in local machine
> consume golangci-linter 1.61.0

- config/externalname.go
- examples/iot/v1beta1/thingtype.yaml
- examples/iot/v1beta2/thingtype.yaml
The aws iot ThingType resource uses a parameter called "name" as its terraform id. Unfortunately, when it was first implemented, it was done using IdentifierFromProvider, which means that creating a new managed resource always attempts to create a new external resource, even if there already is one with the same name. For this particular resource, this results in errors from the AWS api. 
The best external name config would be `config.NameAsIdentifier`, which would remove the redundant `name` property from both `spec.forProvider` and `spec.initProvider`, and initialize the name from `metadata.name`. But that's a breaking api change.
The next best external name config would be `config.TemplatedStringAsIdentifier("", "{{ .parameters.name }}")`, but that will (correctly) set `name` as an …
> Improve external-name config of iot thing type

- apis/ec2/v1beta1/zz_vpcendpoint_terraformed.go
- apis/ec2/v1beta2/zz_vpcendpoint_terraformed.go
- config/ec2/config.go
- examples/ec2/v1beta1/vpcendpointsubnetassociation.yaml
Add `subnet_configuration` to status for a VPC Endpoint.
Fixes #1596 
I have:
We can see for the `VPCEndpoint` uptest run that `status.subnetConfiguration` is set but not lateInitialized to the `spec`.
```shell
2024-12-13T10:31:18.5260960Z     logger.go:42: 10:31:18 | case/3-delete |   kind: VPCEndpoint
2024-12-13T10:31:18.5261951Z     logger.go:42: 10:31:18 | case/3-delete |   metadata:
2024-12-13T10:31:18.5262979Z     logger.go:42: 10:31:18 | case/3-delete |     annotations:
2024-12-13T10:31:18.5264471Z     logger.go:42: 10:31:18 | case/3-delete |       crossplane.io/external-create-pending: "2024-12-13T10:28:15Z"
2024-12-13T10:31:18.5265839Z     logger.go:42: 10:31:18 | case/3-delete |       crossplane.io/external-create-succeeded: "2024-12-13T10:28:15Z"
2024-12-13T10:31:18.5267070Z …
```
> add subnet_configuration to VPCEndpoint LateInit

- config/rds/config.go
This is to ensure global cluster endpoints are exported to connection secrets.
Fixes #
I have:
A local build was deployed to a cluster, an RDS GlobalDatabase was created, and the secret was inspected. The endpoint value was there as expected.
> rds_global_cluster endpoint in connection details

- config/common/common.go
- config/ec2/config.go
- go.mod
- go.sum
Fixes #1579. See https://github.com/upbound/terraform-provider-aws/pull/279 for a detailed explanation of the problem and the fix.
I modularized the custom diff code in https://github.com/crossplane-contrib/provider-upjet-azure/pull/816, so that we can simply call this function to ignore empty diffs, as in [the example](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1625/files#diff-1dd08ae78b69dddf38b311b827ebd655e113ca72c2a63f98c21d459c021a3d0eR56-R58).
I have:
Uptest runs:
1. [examples/ec2/v1beta1/instance.yaml](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12584328521)
2. [examples/ec2/v1beta2/instance.yaml](https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12584874277)
3. …
> Consume EC2 Instance panic fix and address perpetual diff

- AUTHENTICATION.md
Fixes https://github.com/crossplane-contrib/provider-upjet-aws/issues/1529.
Added documentation for EKS Pod Identity as an authentication mechanism for `provider-aws`. 
I have:
I did the testing on an EKS cluster myself, because there was a need to configure EKS Pod Identity for Crossplane, and since no info was present in the documentation, I used some examples https://github.com/crossplane-contrib/provider-upjet-aws/pull/1459 alongside with my own additional configuration
> Added info about EKS Pod Identity as an authentication mechanism

- apis/rds/v1beta1/zz_cluster_terraformed.go
- apis/rds/v1beta2/zz_cluster_terraformed.go
- config/rds/config.go
- examples/rds/v1beta2/cluster.yaml
Disable late init for enabledCloudwatchLogsExports in rds Cluster
I have:
- `examples/rds/v1beta1/cluster.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12932627523
- `examples/rds/v1beta2/cluster.yaml` => https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/12954227675
> Disable lateinit for enabledCloudwatchLogsExports in rds Cluster

- apis/cloudwatchlogs/v1beta1/zz_generated.resolvers.go
- apis/cloudwatchlogs/v1beta1/zz_group_types.go
- config/cloudwatchlogs/config.go
- examples/cloudwatchlogs/v1beta1/group-with-kms.yaml
- internal/clients/zz_partitions_gen.go
Currently, when specifying a reference to an AWS KMS Key in a Cloudwatch logs `Group`, it tries to use the KMS Key ID which does not work. It should use the ARN of the resource.
Despite the confusing parameter name, the TF provider docs do state this [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group):
>[kms_key_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group#kms_key_id-1) - (Optional) The ARN of the KMS Key to use when encrypting log data.
I have:
I have added an additional E2E test to cover this behaviour, let me know if this is suitable.
https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/13188245301
> Use ARN extractor for Cloudwatch log group `kms_key_id` reference

- examples/mq/v1alpha1/user-with-groups.yaml
- go.mod
- go.sum
This PR updates tf provider to the commit `ca3a4c5ba291` and adds a test example with `groups` field for the MQ User resource.
Fixes https://github.com/crossplane-contrib/provider-upjet-aws/issues/1657
I have:
Manually and uptest: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/13241246044
*Note: A Broker reboot is required for any MQ User operations to take effect. After creating 3 User resources here, a reboot is required.*
> Update tf provider to the commit ca3a4c5ba291 and add a test example

- .github/workflows/ci.yml
- .github/workflows/uptest-trigger.yaml
- go.mod
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2024-45341 | Medium |
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2024-45336 | Medium |
| stdlib | `go1.23.3` -> `go1.23.6` | go-module | CVE-2025-22866 | - |
I have:
https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/13245917828
> [release-1.17] Update go version to 1.23.6 [SECURITY]

- config/mq/config.go
- examples/mq/v1beta1/configuration.yaml
- go.mod
- go.sum
Fixes https://github.com/crossplane-contrib/provider-upjet-aws/issues/1449
This PR consumes and dependent to the https://github.com/crossplane/upjet/pull/466.
This PR implements an Update Loop Prevention function for the `aws_mq_configuration` resource. The change addresses the issue where invalid or schema-violating XML data provided in the data field of the resource can result in repeated diffs during reconciliation. This problem occurs because AWS silently sanitizes invalid XML content without notifying management layers.
I have:
https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/13263377111
https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/13263374686
> Add Update Prevent function to `mq_configuraiton` resource for preventing the update loop

- .github/workflows/uptest-trigger.yaml
Prevents member from triggering workflow via PR comment.
I have:
> Prevent member from triggering workflow via PR comment

- .github/workflows/uptest-trigger.yaml
Determine appropriate access for comment-based workflow triggers based on the commenter's repository-level permission, rather than author association (which is a non-intuitive derivation based on membership in the GitHub organization in addition to repository-level permissions).
This aims to ensure trusted actors are able to run their e2e workflows in repositories they maintain, without necessarily requiring membership in the crossplane-contrib organization.
xref https://github.com/crossplane-contrib/provider-upjet-azuread/pull/208
I have:
On a personal fork. https://github.com/jastang/provider-upjet-aws/actions/runs/13634041711
> Check repository permission instead of author association.

- .github/workflows/uptest-trigger.yaml
See https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#get-repository-permissions-for-a-user
If we end up setting up custom roles for something, we could change this to be a check on the `role_name` attribute, but for now this seems simplest.
I have:
> Allow write permission to execute e2e workflow

- apis/ec2/v1beta1/zz_instance_terraformed.go
- apis/ec2/v1beta2/zz_instance_terraformed.go
- config/ec2/config.go
This PR fixes ec2 instance recreation issue after manual termination by ignoring the `cpu_options` and `root_block_device` fields from LateInitializer.
Fixes: https://github.com/crossplane-contrib/provider-upjet-aws/issues/1306
I have:
Tested recreation case manually with `index.docker.io/turkenf/provider-aws:v1.21.0-rc.0.56.gddd4ddd05` and uptest: https://github.com/crossplane-contrib/provider-upjet-aws/actions/runs/13684144410
> Fix ec2 instance recreation issue after manual termination

- .github/workflows/publish-provider-packages.yaml
This PR overrides the machine type for using larger machines for publishing.
I have:
> Use larger machines for publish workflow

- go.mod
- go.sum
This is a small follow-up PR to #1753 to bump the upjet dependency to the latest in its [crossplane-v2](https://github.com/crossplane/upjet/tree/crossplane-v2) branch, now that upjet PR https://github.com/crossplane/upjet/pull/480 has been merged.
I have:
I've manually run `make generate` and saw no difference in functionality, which isn't surprising because this is effectively the same upjet code we'd been testing all along in #1753 😁 
> chore(deps): bump upjet dependency to crossplane-v2 branch

- .github/PULL_REQUEST_TEMPLATE.md
I just set up a clean dev environment, and while I was able to get `make reviewable` to run successfully, it took 55 minutes! It's possible it would have failed on a machine with less RAM available. This seems like an unreasonably high bar to expect from new contributors. I confess that I generally do not run it locally on my own PRs because it takes so long, and because most (all?) of its functionality is also implemented in CI. 
I think there's probably some more adjustments we can make to the language in the template to make this more clear, and I'm also interested in finding ways to improve the new-contributor experience as far as ability to run CI checks, although I understand there are some valid security concerns there. 
Fixes #
I have:
> Update PR template to reference codegen

- cmd/provider/vpclattice/zz_main.go
Fixes the check-diff failure on main
I have:
No changes, just reran `make generate` after the vpclattice provider was added in [one PR](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1767) and the main.go.tmpl file was updated in [another](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1524). 
> Codegen to solve merge conflict

- config/backup/config.go
- examples/backup/v1beta1/selection.yaml
This PR adds a custom diff func for fields that cause loops in the selection resource and adds an example.
```
2025-05-27T22:25:00+03:00	DEBUG	provider-aws	Diff detected	{"uid": "4c7480f8-10f0-47ee-800e-713dc148a8e5", "name": "example-selection", "gvk": "backup.aws.upbound.io/v1beta1, Kind=Selection", "instanceDiff": "*terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{\"condition.0.string_equals.#\":*terraform.ResourceAttrDiff{Old:\"0\", New:\"0\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"condition.0.string_like.#\":*terraform.ResourceAttrDiff{Old:\"0\", New:\"0\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, …
```
> Fix update loop in backup selection resource and add an example

- Makefile
- go.mod
Update go version to 1.24.6
I have:
> Update go version to 1.24.6 [Security]

- apis/cluster/fsx/v1beta1/zz_ontapfilesystem_terraformed.go
- apis/cluster/fsx/v1beta2/zz_ontapfilesystem_terraformed.go
- apis/namespaced/fsx/v1beta1/zz_ontapfilesystem_terraformed.go
- config/cluster/fsx/config.go
- config/namespaced/fsx/config.go
Fix FSX ONTAP filesystem update failures caused by IOPS configuration conflicts during storage capacity updates.
When attempting to increase storage capacity on FSX ONTAP filesystems using Crossplane, operations were failing with the error:
Warning CannotUpdateExternalResource: async update failed: failed to update the resource: BadRequest: Invalid DiskIopsConfiguration provided. IOPS cannot be set with AUTOMATIC mode.
This occurred because the late initialization process was including DiskIopsConfiguration fields that conflict with AWS FSX's AUTOMATIC IOPS mode during updates.
- Added DiskIopsConfiguration to the ignored fields list in late initialization for both v1beta1 and v1beta2 API versions
- Updated the FSX resource configurator to explicitly ignore disk_iops_configuration during …
> fix(fsx): ignore DiskIopsConfiguration in late initialization to prevent conflicts
